
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[375] =
    {   0,
       10,   10,    8,    8,   71,   69,   10,   11,   11,   69,
       69,   59,   58,   69,   61,   62,   56,   55,   67,   54,
       68,   57,   36,   52,   53,   69,   60,   69,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   63,   64,   65,   11,   66,   70,    8,   70,
       10,   47,    0,   39,    0,    3,    5,    0,    0,    0,
        0,    0,    0,    7,    1,    0,   36,   38,   60,   50,
       49,   46,   48,   51,   38,   38,   38,    0,   38,    0,
       38,   38,    0,   38,   38,   38,    0,   24,   24,   38,
        0,   38,    0,   27,   27,   38,   38,    0,   38,    0,

       38,    0,   33,   38,   33,   38,    0,    0,    0,    0,
       40,    0,    0,   24,    0,    0,   33,    0,    0,   24,
        8,    0,    9,    0,   39,    0,    3,    4,    5,    6,
        0,   44,    0,    0,   45,   44,    0,    1,    2,   37,
       38,   38,    0,   38,    0,    0,    0,    0,   38,    0,
       38,    0,   38,    0,    0,   38,    0,   22,   22,   38,
        0,   22,   38,    0,   26,   26,   38,    0,   38,   38,
        0,    0,    0,    0,   38,    0,   32,   32,   38,    0,
       38,    0,    0,    0,    0,    0,   40,    0,   32,   26,
        0,   22,    0,    0,   22,    0,   32,   22,    0,    0,

       43,    0,   38,    0,   38,    0,    0,   38,    0,    0,
       38,    0,   16,   16,   38,   38,   38,   38,    0,    0,
        0,    0,    0,   16,   38,    0,   38,    0,    0,   38,
        0,   38,    0,   38,    0,   38,    0,    0,    0,   38,
        0,   34,   34,   35,   35,    0,    0,   16,   34,    0,
       16,   35,    0,    0,   16,    0,    0,   16,   41,   42,
       41,   12,   12,   13,   13,   12,   38,    0,   12,   38,
        0,   38,    0,   38,    0,   19,   19,   38,    0,   19,
       21,   21,   38,    0,   21,   25,   25,   38,    0,   38,
        0,   38,    0,    0,    0,   38,    0,   21,    0,    0,

       13,    0,   19,   12,   21,   25,    0,   13,   12,   14,
       14,   15,   15,   38,    0,   18,   18,   38,    0,   18,
       38,    0,   38,    0,   38,    0,   38,    0,    0,    0,
       31,   31,   15,   14,    0,   14,   15,    0,   14,   38,
        0,   20,   20,   20,   38,    0,   38,    0,   29,   29,
       38,    0,   29,   29,    0,   20,   20,   17,   17,   23,
       23,   38,    0,   38,    0,    0,   17,   17,   28,   28,
       30,   30,   28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       26,   31,   32,   26,   26,   33,   34,   35,   36,   37,
       26,   38,   39,   40,   41,   42,   43,   26,   26,   26,
       44,   45,   46,    1,   26,    1,   25,   26,   27,   28,

       29,   30,   26,   31,   32,   26,   26,   33,   34,   35,
       36,   37,   26,   38,   39,   40,   41,   42,   43,   26,
       26,   26,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[385] =
    {   0,
        0,    0,   47,   48,  900,  901,  897,  901,  901,  875,
       46,  901,  901,  888,  901,  901,  883,  901,  901,  901,
       28,   41,   38,  872,  901,  871,   43,  870,  873,   51,
       50,   52,   53,   56,   54,   64,   58,   78,   76,   88,
       77,   89,  104,  901,  901,  126,  901,  901,  888,  105,
      888,  901,  121,  901,  132,  886,  885,   74,  870,   26,
       81,  869,  135,  901,  882,  865,   63,  837,  901,  901,
      901,  901,  901,  901,  834,  115,  109,  140,  124,  130,
      156,  157,  152,  120,  163,  162,  151,  833,  901,  171,
       84,  173,   98,  830,  901,  174,  177,  170,  175,  180,

      184,  186,  829,  188,  189,  195,  191,  232,  234,  242,
      901,  208,  217,  901,  224,  222,  228,  226,  234,  264,
      844,  241,  901,  265,  275,  280,  842,  901,  841,  901,
      236,  901,  258,  825,  901,  901,  291,  837,  901,  801,
      276,  292,  284,  282,  273,  279,  289,  303,  297,  185,
      307,  304,  327,  317,  334,  319,  302,  800,  901,  349,
      308,  335,  353,  323,  796,  901,  354,  344,  361,  362,
      357,  343,  359,  369,  371,  220,  795,  901,  379,  305,
      385,   99,  733,  408,  414,  419,  422,  396,  347,  398,
      409,  375,  413,  410,  388,  422,  425,  449,  704,  666,

      901,  660,  424,  367,  456,  393,  445,  450,   97,  463,
      452,  447,  640,  901,  477,  484,  486,  487,  482,  474,
      473,  478,  481,  506,  498,  397,  504,  437,  508,  512,
      495,  521,  499,  532,  516,  530,  524,  533,  536,  544,
      528,  597,  901,  592,  901,  539,  548,  550,  542,  555,
      549,  556,  567,  573,  901,  577,  570,  601,  901,  901,
      901,  560,  901,  558,  901,  901,  574,  576,  580,  598,
      590,  604,  595,  613,  606,  556,  901,  623,  605,  622,
      555,  901,  636,  616,  618,  531,  901,  638,  627,  639,
      625,  650,  644,  648,  653,  655,  654,  651,  656,  663,

      665,  680,  671,  901,  678,  682,  676,  674,  706,  505,
      901,  433,  901,  697,  679,  430,  901,  701,  694,  708,
      714,  681,  718,  675,  724,  719,  732,  711,  728,  734,
      428,  901,  901,  729,  742,  901,  720,  755,  756,  752,
      716,  374,  901,  722,  770,  753,  779,  764,  368,  901,
      775,  761,  768,  773,  787,  901,  795,  232,  901,  208,
      901,  791,  769,  809,  802,  803,  807,  808,  168,  901,
      101,  901,  901,  901,  857,  860,  862,   78,  865,  868,
      871,  874,  877,  880
    } ;

static const flex_int16_t yy_def[385] =
    {   0,
      374,    1,  375,  375,  374,  374,  374,  374,  374,  374,
      376,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  377,  374,  374,  374,  374,  374,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  379,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  376,  374,  380,  381,  382,  374,  374,  374,
      374,  374,  374,  374,  383,  374,  377,  377,  374,  374,
      374,  374,  374,  374,  378,  378,  378,  374,  378,  374,
      378,  378,  374,  378,  378,  378,  374,  378,  374,  378,
      374,  378,  374,  378,  374,  378,  378,  374,  378,  374,

      378,  374,  378,  378,  374,  378,  374,  379,  379,  384,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  376,  376,  380,  381,  374,  382,  374,
      374,  374,  374,  374,  374,  374,  374,  383,  374,  374,
      378,  378,  374,  378,  374,  374,  374,  374,  378,  374,
      378,  374,  378,  374,  374,  378,  374,  378,  374,  378,
      374,  374,  378,  374,  378,  374,  378,  374,  378,  378,
      374,  374,  374,  374,  378,  374,  378,  374,  378,  374,
      378,  374,  374,  379,  379,  384,  379,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  378,  374,  378,  374,  374,  378,  374,  374,
      378,  374,  378,  374,  378,  378,  378,  378,  374,  374,
      374,  374,  374,  374,  378,  374,  378,  374,  374,  378,
      374,  378,  374,  378,  374,  378,  374,  374,  374,  378,
      374,  378,  374,  378,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  378,  374,  378,  374,  374,  378,  374,  374,  378,
      374,  378,  374,  378,  374,  378,  374,  378,  374,  374,
      378,  374,  378,  374,  374,  378,  374,  378,  374,  378,
      374,  378,  374,  374,  374,  378,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  378,
      374,  378,  374,  378,  374,  378,  374,  378,  374,  374,
      378,  374,  378,  374,  378,  374,  378,  374,  374,  374,
      378,  374,  374,  374,  374,  374,  374,  374,  374,  378,
      374,  378,  374,  374,  378,  374,  378,  374,  378,  374,
      378,  374,  374,  374,  374,  374,  374,  378,  374,  378,
      374,  378,  374,  378,  374,  374,  374,  374,  378,  374,
      378,  374,  374,    0,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374
    } ;

static const flex_int16_t yy_nxt[951] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   11,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   30,   31,   32,   33,
       29,   34,   35,   29,   36,   37,   38,   39,   40,   41,
       29,   29,   42,   43,    6,   44,   45,   46,   47,   49,
       49,   54,   58,   64,   66,   54,   67,   59,   65,   50,
       50,  133,   60,   61,   71,   72,   73,   62,   68,   68,
       68,   68,   68,  133,   68,   63,   68,   84,   79,   66,
       75,   67,   68,   76,   81,   88,   82,   94,   85,   90,
       55,   77,   92,   86,   68,   68,   68,   80,   78,   83,

       87,   91,   96,   89,   99,   95,   68,   68,  131,  109,
      164,   93,  103,  109,  104,   97,  101,  122,  134,   68,
      106,  131,  123,  100,  105,   98,   54,   68,  134,  245,
       54,  164,  268,   68,   53,  102,  107,  125,   68,  141,
      166,  125,   68,  142,  268,  166,  245,  144,  110,  111,
      112,  136,  156,  149,  113,  114,  145,  107,  115,  150,
      116,  117,  143,  118,  146,   55,  119,  157,  147,  131,
      133,  150,  134,  120,   68,   68,  126,  150,  145,  154,
       68,   68,  137,  157,  153,  161,   68,  148,  159,   68,
      152,   68,   68,   68,  151,   68,  160,  163,  162,  155,

      158,  172,   68,  152,  154,  173,   68,  168,  169,  161,
      159,  167,  170,   68,  175,  165,  212,  174,  164,  176,
      166,  168,  176,  177,  171,  178,   68,  176,  179,  180,
      182,  178,  212,  178,  181,  180,  180,  183,  182,  183,
      157,  183,  182,  183,  108,  168,  150,  185,  146,  154,
       68,  185,  147,  122,  164,  188,  189,  172,  123,  166,
      241,  173,  152,  199,  190,  159,  180,  241,  161,  154,
       54,  191,  145,  193,   54,  192,  110,  111,  110,  111,
       54,  194,   53,  199,   54,  125,  186,  187,  146,  125,
      164,  154,  147,  150,   68,  172,  157,  200,  161,  173,

       68,  195,  196,  197,  180,  200,  166,  201,  206,   55,
       68,  198,  209,  206,  203,   68,  205,  204,  199,   55,
      209,  208,  204,  204,  126,   68,  204,  206,  211,  209,
      200,  207,  214,  243,  228,  213,  206,   68,  202,  206,
      226,  204,  209,  220,  212,   68,  221,  231,  222,  226,
      210,  214,  243,  215,  214,  228,  216,  225,  217,  223,
      220,  228,  214,  221,  219,  222,  226,   68,  233,  218,
      231,   68,   68,  226,  219,  227,  223,  230,  232,   68,
       68,  224,  229,  237,  235,  237,   68,  241,  236,   68,
      235,  233,   68,  233,  241,  237,  228,   68,  235,  231,

      231,  233,  234,   68,  238,  263,  237,  242,  235,  237,
      235,  240,  233,  183,  263,  244,  239,  183,  241,  183,
      233,  108,  231,  183,  185,  282,  243,  183,  185,  212,
      265,  183,  245,  206,  226,  233,  228,  214,  241,  237,
      265,  243,   68,  246,  282,  247,   68,  204,   68,  209,
      214,   68,  110,  111,  235,  245,  248,  250,  110,  111,
      249,  209,  262,  186,  187,  241,  110,  111,   68,  251,
       68,  263,  252,  253,   68,  254,  284,  255,  221,  245,
      256,  271,  265,  263,  284,  267,  270,  257,  209,  241,
      235,  223,  266,  264,  271,   68,  258,  268,  268,  271,

      265,  263,   68,  265,   68,   68,  273,  277,  275,  272,
      269,  277,  279,  279,  273,  276,   68,  275,  278,  274,
      275,  273,   68,   68,  273,  277,  281,  287,  279,  280,
       68,  275,  289,  277,  279,  277,  282,  279,  273,   68,
      291,  275,  287,  283,  286,  282,  289,  284,   68,   68,
       68,  284,  293,  280,  288,  285,  290,  291,  292,  287,
      291,  293,   68,  291,  293,  297,  291,  282,  289,  289,
      293,  293,  289,   68,   68,  297,   68,  293,   68,  291,
      294,  296,  271,  295,  268,  297,  298,  265,  263,  294,
      268,  297,   68,  297,  284,  299,  268,  266,  282,  287,

      289,  293,  300,  297,  265,  273,  277,  310,  263,  311,
       68,  271,  284,  311,  301,   68,   68,  304,  313,  315,
      302,  311,   68,  311,  303,  291,  312,  311,  314,  305,
      277,   68,  279,  306,  289,  271,  307,  313,  308,  263,
      284,   68,  315,  317,  319,  313,  315,  322,  309,  322,
      316,  315,  319,  317,   68,  324,   68,   68,   68,  317,
      317,  319,  318,  322,  326,  322,  323,  321,   68,  320,
      319,  328,  326,   68,  324,  328,  261,  327,  325,  324,
      328,  324,  260,  322,  313,  324,  326,  326,  332,  331,
      332,  328,  326,  324,  322,  329,  311,  328,  324,  313,

      330,  332,  332,  333,  315,  328,  315,  328,  332,  311,
      334,  322,  324,  317,  348,   68,  346,  341,  313,   68,
      259,  332,  348,  336,  343,  328,  341,  335,  346,  315,
      315,  342,   68,  328,  337,  340,   68,  322,  343,  311,
      332,  343,   68,  317,  341,  338,  341,  350,  343,  345,
       68,  352,  349,  339,  359,  344,  350,  347,  352,  348,
      359,  346,  350,  359,  346,  348,  350,  348,  352,  359,
       68,  350,  351,  348,  352,  353,  346,  346,  111,  352,
      341,  354,  352,  350,  350,  343,  343,  361,   68,  355,
      358,  346,  363,   68,  341,  348,  352,   68,  365,  359,

      361,  363,  356,  357,  360,  365,  370,  362,  365,   68,
      365,  363,  364,   68,   68,  365,  370,  361,   68,  140,
      366,  361,  365,  363,  365,  359,  363,   68,  369,  361,
      372,  372,  365,  359,  367,  372,  372,  371,  370,  139,
      370,  201,  368,  130,  128,  370,  121,   68,   68,  372,
      373,   68,   68,  374,  372,  373,  372,   48,   48,   48,
       53,   53,   53,   68,   68,  108,  108,  108,  124,  124,
      124,  127,  127,  127,  129,  129,  129,  138,  138,  138,
      184,  184,  184,  140,  139,  135,  132,  130,  128,   51,
      121,   68,   74,   70,   69,   57,   56,   52,   51,  374,

        5,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static const flex_int16_t yy_chk[951] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   11,   21,   22,   23,   11,   23,   21,   22,    3,
        4,   60,   21,   21,   27,   27,   27,   21,   31,   30,
       32,   33,   35,   60,   34,   21,   37,   33,   31,   67,
      378,   67,   36,   30,   32,   34,   32,   37,   33,   35,
       11,   30,   36,   33,   39,   41,   38,   31,   30,   32,

       33,   35,   38,   34,   39,   37,   40,   42,   58,   43,
       91,   36,   41,   43,   41,   38,   40,   50,   61,  371,
       42,   58,   50,   39,   41,   38,   53,   77,   61,  182,
       53,   91,  209,   76,   55,   40,   42,   55,   84,   76,
       93,   55,   79,   76,  209,   93,  182,   77,   43,   43,
       46,   63,   84,   79,   46,   46,   77,   46,   46,   80,
       46,   46,   76,   46,   78,   53,   46,   84,   78,   63,
       63,   79,   63,   46,   81,   82,   55,   80,   78,   83,
       86,   85,   63,   87,   82,   87,  369,   78,   87,   90,
       83,   92,   96,   99,   81,   97,   86,   90,   87,   83,

       85,   98,  101,   81,   82,   98,  104,   98,   97,   86,
       85,   96,   97,  106,   99,   92,  150,   98,   90,  100,
       92,   96,   99,  101,   97,  102,  360,  100,  104,  105,
      107,  101,  150,  102,  106,  104,  105,  108,  107,  109,
      112,  108,  106,  109,  110,  112,  113,  110,  115,  116,
      358,  110,  115,  122,  117,  112,  113,  118,  122,  113,
      176,  118,  115,  131,  113,  117,  118,  176,  119,  116,
      124,  115,  119,  118,  124,  117,  108,  108,  109,  109,
      125,  119,  126,  131,  125,  126,  110,  110,  120,  126,
      120,  120,  120,  120,  141,  120,  120,  133,  120,  120,

      144,  120,  120,  120,  120,  133,  120,  137,  143,  124,
      142,  120,  145,  147,  141,  149,  142,  146,  137,  125,
      145,  144,  143,  141,  126,  151,  146,  148,  149,  144,
      137,  143,  152,  180,  161,  151,  147,  156,  137,  142,
      157,  148,  148,  154,  149,  153,  154,  164,  154,  157,
      148,  152,  180,  153,  151,  161,  153,  156,  153,  154,
      155,  162,  155,  155,  154,  155,  156,  160,  168,  153,
      164,  163,  167,  162,  153,  160,  155,  163,  167,  169,
      170,  155,  162,  171,  172,  173,  349,  189,  170,  175,
      172,  168,  342,  174,  189,  174,  160,  179,  171,  192,

      163,  167,  169,  181,  171,  204,  173,  179,  169,  170,
      174,  175,  195,  184,  204,  181,  174,  184,  175,  185,
      188,  186,  192,  185,  186,  226,  179,  187,  186,  190,
      206,  187,  181,  191,  188,  195,  194,  191,  190,  193,
      206,  193,  203,  188,  226,  190,  331,  191,  316,  194,
      196,  312,  184,  184,  193,  197,  191,  194,  185,  185,
      193,  196,  203,  186,  186,  197,  187,  187,  208,  196,
      211,  203,  197,  198,  205,  198,  228,  198,  198,  198,
      198,  212,  207,  207,  228,  208,  211,  198,  198,  198,
      198,  198,  207,  205,  212,  215,  198,  208,  210,  211,

      210,  210,  216,  205,  217,  218,  220,  222,  221,  215,
      210,  219,  223,  219,  219,  217,  225,  219,  218,  216,
      221,  220,  227,  310,  215,  222,  225,  231,  223,  219,
      230,  216,  233,  217,  218,  224,  229,  224,  224,  232,
      235,  224,  231,  227,  230,  225,  233,  229,  236,  286,
      234,  227,  237,  224,  232,  229,  234,  238,  236,  230,
      239,  238,  240,  235,  239,  241,  249,  246,  232,  239,
      249,  237,  246,  281,  276,  241,  264,  236,  262,  234,
      238,  240,  247,  239,  251,  247,  246,  248,  248,  249,
      250,  240,  267,  252,  250,  247,  251,  248,  257,  253,

      253,  254,  250,  252,  253,  254,  256,  267,  257,  268,
      244,  256,  254,  269,  253,  242,  270,  257,  271,  273,
      254,  267,  272,  268,  256,  258,  270,  269,  272,  258,
      258,  274,  258,  258,  258,  258,  258,  271,  258,  258,
      258,  278,  273,  275,  279,  270,  280,  284,  258,  285,
      274,  272,  279,  275,  283,  289,  288,  290,  213,  280,
      274,  280,  278,  284,  291,  285,  288,  283,  292,  280,
      278,  293,  291,  296,  289,  294,  202,  292,  290,  298,
      295,  295,  200,  283,  299,  288,  290,  294,  297,  296,
      299,  293,  295,  301,  300,  294,  300,  292,  298,  303,

      295,  297,  296,  299,  302,  305,  306,  302,  308,  307,
      300,  302,  301,  307,  324,  314,  322,  315,  303,  318,
      199,  308,  324,  307,  319,  305,  315,  302,  322,  306,
      309,  318,  321,  309,  309,  314,  323,  309,  320,  309,
      309,  319,  325,  309,  314,  309,  320,  326,  318,  321,
      327,  328,  325,  309,  341,  320,  329,  323,  328,  337,
      344,  321,  330,  341,  334,  323,  326,  337,  329,  344,
      340,  325,  327,  330,  330,  329,  334,  335,  183,  327,
      335,  330,  335,  338,  339,  338,  339,  346,  345,  335,
      340,  339,  348,  351,  339,  339,  339,  347,  352,  340,

      346,  354,  338,  339,  345,  353,  363,  347,  352,  362,
      354,  348,  351,  177,  165,  353,  363,  345,  158,  140,
      354,  355,  351,  357,  355,  355,  347,  364,  362,  357,
      365,  366,  357,  357,  355,  367,  368,  364,  362,  138,
      366,  134,  357,  129,  127,  368,  121,  103,   94,  365,
      366,   88,   75,   68,  367,  368,  364,  375,  375,  375,
      376,  376,  376,  377,  377,  379,  379,  379,  380,  380,
      380,  381,  381,  381,  382,  382,  382,  383,  383,  383,
      384,  384,  384,   66,   65,   62,   59,   57,   56,   51,
       49,   29,   28,   26,   24,   17,   14,   10,    7,    5,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pascalDSLwin32.l"
#line 2 "pascalDSLwin32.l"
// ----------------------------------------------------------------------------
// File   : dbaseDSLwin32.l
// Author : Jens Kallup (c) 2023-07.01
// License: all rights reserved.
// ----------------------------------------------------------------------------
# include "../common.h"
# include "pascalDSLwin32.tab.h"

// ----------------------------------------------------------------------------
// parser variables and constants:
// ----------------------------------------------------------------------------

typedef void (*addParserErrorText)(char* message);
static addParserErrorText m_addParserErrorText ;

int count(void);
void* addTextPtr;

int yy_col = 1;
int yy_row = 1;

int        yy_pascal_win32_count(void)        { return yy_row; }
int EXPORT yy_pascal_win32_lex_get_line(void) { return yy_pascal_win32_count(); }
int EXPORT yy_pascal_win32_lex_getlines(void) { return yy_pascal_win32_count(); }

extern void yyerror(const char* msg);

#line 800 "lex.yy.c"

#line 802 "lex.yy.c"

#define INITIAL 0
#define Comment1 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 69 "pascalDSLwin32.l"


#line 1023 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 375 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 901 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 71 "pascalDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 72 "pascalDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "pascalDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 75 "pascalDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "pascalDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 78 "pascalDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 80 "pascalDSLwin32.l"
{ BEGIN(Comment1); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 81 "pascalDSLwin32.l"
{ yy_row += 1;     yy_row++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 82 "pascalDSLwin32.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "pascalDSLwin32.l"
{ /* empty */ }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 85 "pascalDSLwin32.l"
{ yy_col = 1;      yy_row++; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "pascalDSLwin32.l"
{ return TOK_CLASS;     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "pascalDSLwin32.l"
{ return TOK_CLEAR;     }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "pascalDSLwin32.l"
{ return TOK_CUSTOM;    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "pascalDSLwin32.l"
{ return TOK_DEFINE;    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "pascalDSLwin32.l"
{ return TOK_ELSE;      }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "pascalDSLwin32.l"
{ return TOK_ENDCLASS;  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "pascalDSLwin32.l"
{ return TOK_ENDFOR;    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "pascalDSLwin32.l"
{ return TOK_ENDIF;     }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "pascalDSLwin32.l"
{ return TOK_ENDWITH;   }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "pascalDSLwin32.l"
{ return TOK_FALSE;     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "pascalDSLwin32.l"
{ return TOK_FOR;       }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "pascalDSLwin32.l"
{ return TOK_FUNCTION;  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "pascalDSLwin32.l"
{ return TOK_IF;        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "pascalDSLwin32.l"
{ return TOK_LOCAL;     }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "pascalDSLwin32.l"
{ return TOK_NEW;       }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "pascalDSLwin32.l"
{ return TOK_OF;        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 103 "pascalDSLwin32.l"
{ return TOK_PARAMETER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 104 "pascalDSLwin32.l"
{ return TOK_PRIVATE;   }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 105 "pascalDSLwin32.l"
{ return TOK_PROCEDURE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "pascalDSLwin32.l"
{ return TOK_RETURN;    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 107 "pascalDSLwin32.l"
{ return TOK_SET;       }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 108 "pascalDSLwin32.l"
{ return TOK_TO;        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "pascalDSLwin32.l"
{ return TOK_TRUE;      }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "pascalDSLwin32.l"
{ return TOK_WITH;      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "pascalDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "pascalDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "pascalDSLwin32.l"
{
	// -----------------------------------
	// pattern for: identifier's ...
	// -----------------------------------
	yylval.node_and_value.name = (char*) malloc( strlen( yytext ) + 1); strcpy(
	yylval.node_and_value.name, yytext);
	
	return TOK_ID;
}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 125 "pascalDSLwin32.l"
{
	// -----------------------------------
	// pattern for: "Hello World"
	// pattern for: 'Hello World'
	// -----------------------------------
	yylval.node_and_value.name = (char*) malloc( strlen( yytext ) + 1); strcpy(
	yylval.node_and_value.name, yytext );
	
	return TOK_STRING;
}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 136 "pascalDSLwin32.l"
{
	// -----------------------------------
	// pattern for:  [ "Hallo \" World" ]
	// pattern for:  [ 'Hello \' World' ]
	// -----------------------------------
	char* str = yytext;
	int   len = 0;
	
	if (str[0] == '\'' || str[0] == '\"')
		str++;
		
	len = strlen(str);
	
	if (str[len - 1] == '\'' || str[len - 1] == '\"')
		str[len - 1] =  '\0' ;
	
	yylval.node_and_value.name = (char*) malloc( strlen( str ) + 1); strcpy(
	yylval.node_and_value.name, str );
	
	return TOK_STRING_BRACE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "pascalDSLwin32.l"
{ return TOK_AND;    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 159 "pascalDSLwin32.l"
{ return TOK_NOT;    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "pascalDSLwin32.l"
{ return TOK_OR;     }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "pascalDSLwin32.l"
{ return TOK_FALSE;  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "pascalDSLwin32.l"
{ return TOK_TRUE;   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 165 "pascalDSLwin32.l"
{ return TOK_EQEQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 166 "pascalDSLwin32.l"
{ return TOK_LTGT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 167 "pascalDSLwin32.l"
{ return TOK_EQGT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 168 "pascalDSLwin32.l"
{ return TOK_EQLT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 169 "pascalDSLwin32.l"
{ return TOK_LTEQ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 170 "pascalDSLwin32.l"
{ return TOK_GTEQ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 172 "pascalDSLwin32.l"
{ return ':'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 173 "pascalDSLwin32.l"
{ return ';'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 174 "pascalDSLwin32.l"
{ return '-'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 175 "pascalDSLwin32.l"
{ return '+'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 176 "pascalDSLwin32.l"
{ return '*'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 177 "pascalDSLwin32.l"
{ return '/'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 178 "pascalDSLwin32.l"
{ return '%'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 180 "pascalDSLwin32.l"
{ return '#'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 182 "pascalDSLwin32.l"
{ return TOK_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 184 "pascalDSLwin32.l"
{ return '('; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 185 "pascalDSLwin32.l"
{ return ')'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 186 "pascalDSLwin32.l"
{ return '['; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 187 "pascalDSLwin32.l"
{ return ']'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 188 "pascalDSLwin32.l"
{ return '{'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 189 "pascalDSLwin32.l"
{ return '}'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 190 "pascalDSLwin32.l"
{ return ','; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 191 "pascalDSLwin32.l"
{ return '.'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 193 "pascalDSLwin32.l"
{
    char buffer[200];
    sprintf( buffer, "Unrecognized character: %s\n", yytext );
    yyerror(buffer);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
#line 199 "pascalDSLwin32.l"
{ return TOK_YYEOF; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 200 "pascalDSLwin32.l"
ECHO;
	YY_BREAK
#line 1483 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 375 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 375 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 374);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "pascalDSLwin32.l"


void EXPORT
yy_pascal_win32_lex_parser_error (void (* func)(const char *message)) {
	m_addParserErrorText =         func;
}

int yywrap(void) { return 1; }

void yyerror(const char* m)
{
	char * buffer = (char *) malloc(1024);
	char * number = (char *) malloc( 255);
	
	itoa(yy_row,number,10);
	
	strcpy( buffer, "error in line: ");
	strcat( buffer, number);
	strcat( buffer, ": ");
	strcat( buffer, m);

	m_addParserErrorText(buffer);
}

BOOL EXPORT
yy_pascal_win32_lex_main(
    char* filename,
    char* tempDir )
{
    BOOL   result = FALSE;
    char * buffer;

	// ------------------------------------------
	// try to open file, saved before ...
	// ------------------------------------------
    if (!(yyin = fopen(filename,"r"))) {
        buffer = (char*) malloc(100);
    
        sprintf(buffer, "could not open file: %s", filename);
        m_addParserErrorText(buffer);
    
        free(buffer);
        return false;
    }

    yy_row = 1;
    yy_col = 1;

	// ------------------------------------------
	// start the race run ...
	// ------------------------------------------
	node_head        = (struct node *) malloc( sizeof( struct node ) );
	node_new         = (struct node *) malloc( sizeof( struct node ) ); // dummy to point head itself
	node_head->token = (       char *) malloc( 8 );
	strcpy( node_head->token, "root" );
	
	// ------------------------
	// root/first record item
	// ------------------------
	node_new->prev = node_head;
	node_new->next = NULL;
	
	// ------------------------
	// call parser ...
	// ------------------------
	result = yyparse();
	
	fclose(yyin);
	return result;
}

void EXPORT
yy_pascal_win32_lex_close(void) {
    fclose(yyin);
}

