
#line 2 "lex.pascal.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pascal_create_buffer
#define yy_delete_buffer pascal_delete_buffer
#define yy_scan_buffer pascal_scan_buffer
#define yy_scan_string pascal_scan_string
#define yy_scan_bytes pascal_scan_bytes
#define yy_init_buffer pascal_init_buffer
#define yy_flush_buffer pascal_flush_buffer
#define yy_load_buffer_state pascal_load_buffer_state
#define yy_switch_to_buffer pascal_switch_to_buffer
#define yypush_buffer_state pascalpush_buffer_state
#define yypop_buffer_state pascalpop_buffer_state
#define yyensure_buffer_stack pascalensure_buffer_stack
#define yy_flex_debug pascal_flex_debug
#define yyin pascalin
#define yyleng pascalleng
#define yylex pascallex
#define yylineno pascallineno
#define yyout pascalout
#define yyrestart pascalrestart
#define yytext pascaltext
#define yywrap pascalwrap
#define yyalloc pascalalloc
#define yyrealloc pascalrealloc
#define yyfree pascalfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define pascal_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer pascal_create_buffer
#endif

#ifdef yy_delete_buffer
#define pascal_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer pascal_delete_buffer
#endif

#ifdef yy_scan_buffer
#define pascal_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer pascal_scan_buffer
#endif

#ifdef yy_scan_string
#define pascal_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string pascal_scan_string
#endif

#ifdef yy_scan_bytes
#define pascal_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes pascal_scan_bytes
#endif

#ifdef yy_init_buffer
#define pascal_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer pascal_init_buffer
#endif

#ifdef yy_flush_buffer
#define pascal_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer pascal_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define pascal_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state pascal_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define pascal_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer pascal_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define pascalpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state pascalpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define pascalpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state pascalpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define pascalensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack pascalensure_buffer_stack
#endif

#ifdef yylex
#define pascallex_ALREADY_DEFINED
#else
#define yylex pascallex
#endif

#ifdef yyrestart
#define pascalrestart_ALREADY_DEFINED
#else
#define yyrestart pascalrestart
#endif

#ifdef yylex_init
#define pascallex_init_ALREADY_DEFINED
#else
#define yylex_init pascallex_init
#endif

#ifdef yylex_init_extra
#define pascallex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra pascallex_init_extra
#endif

#ifdef yylex_destroy
#define pascallex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy pascallex_destroy
#endif

#ifdef yyget_debug
#define pascalget_debug_ALREADY_DEFINED
#else
#define yyget_debug pascalget_debug
#endif

#ifdef yyset_debug
#define pascalset_debug_ALREADY_DEFINED
#else
#define yyset_debug pascalset_debug
#endif

#ifdef yyget_extra
#define pascalget_extra_ALREADY_DEFINED
#else
#define yyget_extra pascalget_extra
#endif

#ifdef yyset_extra
#define pascalset_extra_ALREADY_DEFINED
#else
#define yyset_extra pascalset_extra
#endif

#ifdef yyget_in
#define pascalget_in_ALREADY_DEFINED
#else
#define yyget_in pascalget_in
#endif

#ifdef yyset_in
#define pascalset_in_ALREADY_DEFINED
#else
#define yyset_in pascalset_in
#endif

#ifdef yyget_out
#define pascalget_out_ALREADY_DEFINED
#else
#define yyget_out pascalget_out
#endif

#ifdef yyset_out
#define pascalset_out_ALREADY_DEFINED
#else
#define yyset_out pascalset_out
#endif

#ifdef yyget_leng
#define pascalget_leng_ALREADY_DEFINED
#else
#define yyget_leng pascalget_leng
#endif

#ifdef yyget_text
#define pascalget_text_ALREADY_DEFINED
#else
#define yyget_text pascalget_text
#endif

#ifdef yyget_lineno
#define pascalget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno pascalget_lineno
#endif

#ifdef yyset_lineno
#define pascalset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno pascalset_lineno
#endif

#ifdef yywrap
#define pascalwrap_ALREADY_DEFINED
#else
#define yywrap pascalwrap
#endif

#ifdef yyalloc
#define pascalalloc_ALREADY_DEFINED
#else
#define yyalloc pascalalloc
#endif

#ifdef yyrealloc
#define pascalrealloc_ALREADY_DEFINED
#else
#define yyrealloc pascalrealloc
#endif

#ifdef yyfree
#define pascalfree_ALREADY_DEFINED
#else
#define yyfree pascalfree
#endif

#ifdef yytext
#define pascaltext_ALREADY_DEFINED
#else
#define yytext pascaltext
#endif

#ifdef yyleng
#define pascalleng_ALREADY_DEFINED
#else
#define yyleng pascalleng
#endif

#ifdef yyin
#define pascalin_ALREADY_DEFINED
#else
#define yyin pascalin
#endif

#ifdef yyout
#define pascalout_ALREADY_DEFINED
#else
#define yyout pascalout
#endif

#ifdef yy_flex_debug
#define pascal_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug pascal_flex_debug
#endif

#ifdef yylineno
#define pascallineno_ALREADY_DEFINED
#else
#define yylineno pascallineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[422] =
    {   0,
       13,   13,    8,    8,   11,   11,   59,   57,   13,   14,
       14,   57,   57,   56,   56,   55,   56,   52,   54,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   14,   58,
        8,   58,   11,   58,   13,    3,   10,    5,    7,    1,
       53,   52,    0,    0,    0,    0,    0,    0,    0,    0,
       21,   21,    0,    0,    0,    0,    0,    0,    0,    0,
       30,   31,   30,    0,    0,    0,    0,    0,   36,   37,

       36,    0,    0,    0,    0,    0,    0,   45,    0,   45,
        0,    0,    0,    0,    0,   51,   51,   51,   51,   51,
       51,   51,   21,   51,   51,   51,   51,   51,   51,   30,
       31,   51,   51,   51,   51,   36,   37,   51,   51,   51,
       51,   51,   45,   51,   51,   51,   51,   51,    0,    0,
       30,    0,    0,   31,   21,   37,   21,    8,    0,    9,
       11,   12,    0,    3,    4,    5,    6,    1,    2,   53,
       15,    0,   15,    0,    0,    0,    0,   20,    0,   20,
        0,   24,   24,    0,   26,    0,   26,    0,    0,   33,
       34,   35,   34,    0,    0,    0,    0,    0,    0,   43,

        0,    0,    0,    0,   48,    0,    0,    0,   15,   51,
       51,   51,   51,   20,   51,   51,   24,   51,   26,   51,
       51,   51,   33,   34,   35,   51,   51,   51,   51,   43,
       51,   51,   51,   48,   51,   51,   48,   43,    0,   34,
       20,   15,   15,   35,   26,    0,    0,   15,    0,    0,
       26,    0,   35,   15,    0,    0,   18,    0,   18,    0,
       23,   25,    0,    0,   25,   29,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   44,   46,   44,    0,    0,
       50,   50,   51,   51,   18,   51,   51,   23,   25,   51,
       51,   29,   51,   51,   51,   51,   51,   51,   44,   46,

       51,   51,   50,   18,   18,    0,   44,   25,   29,    0,
        0,    0,   46,    0,   18,   29,    0,   18,    0,   44,
       29,   18,   16,   17,   19,    0,    0,    0,    0,   32,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   47,
       49,   16,   17,   19,   51,   51,   51,   32,   51,   51,
       51,   51,   51,   47,   49,   32,   17,   19,   19,   16,
        0,   19,   16,    0,   32,   17,    0,   49,   32,    0,
       19,   16,   22,    0,    0,    0,   38,    0,    0,    0,
       38,   38,   41,   42,   41,   22,   51,   51,   38,   51,
       51,   41,   42,   22,   38,    0,   42,   41,   22,   38,

       22,   27,    0,   27,    0,   40,   40,   27,   51,   51,
       40,    0,   27,   28,    0,   28,   51,   28,   39,   39,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    5,    1,    6,
        7,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,    1,
        1,    1,    1,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   46,   53,   54,   55,   56,   57,   58,   46,
       59,   46,    1,   60,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[427] =
    {   0,
        0,    0,   58,   59,   60,   61,  315, 1764,  308, 1764,
     1764,  293,  277,  271, 1764, 1764,   62,   60, 1764,   45,
       46,   62,   56,   61,   69,   52,   58,   67,   66,   87,
      103,  104,  105,  109,  108,  110,  116,  117,  121,  153,
      158,  169,  157,  170,  183,  148,  205,  209,  210,  199,
      221,  227,  226,  241,  261,  246,  263,  272,  318, 1764,
      274,   81,  263,  135,  256,  249, 1764,  228, 1764,  213,
      197,   70,  244,  159,  289,  271,  293,  173,  325,  215,
      144,  323,  313,  290,  358,  336,  334,  276,  361,  279,
     1764, 1764, 1764,  366,  375,  347,  365,  374, 1764, 1764,

     1764,  353,  372,  388,  402,  378,  383, 1764,  106,  411,
      396,  406,  419,  405,  423,  417,  440,  442,  454,  455,
      446,  460,  477,  462,  481,  498,  471,  483,  500,  499,
      509,  518,  522,  517,  534,  523,  524,  540,  544,  546,
      560,  561,  566,  578,  582,  583,  595,  597,  615,  627,
     1764,  639,  640,  579,  683,  643,  728,  198,  301, 1764,
      188, 1764,  147,  187, 1764,  146, 1764,   93, 1764,   78,
     1764,  626,  646,  644,  657,  654,  671, 1764,  666,  680,
      701, 1764,  729,  731,  674,  735,  758,  600,  746, 1764,
     1764, 1764, 1764,  760,  783,  784,  677,  773,  791, 1764,

      775,  793,  809,  792, 1764,  769,  802,  816,  651,  840,
      838,  844,  818,  694,  852,  854,  827,  867,  861,  876,
      862,  890,  880,  896,  898,  905,  916,  911,  934,  917,
      918,  954,  940,  927,  961,  952,  978,  982,  981,  839,
      996, 1764,  966,  770, 1008, 1007, 1023, 1764, 1032, 1013,
     1040, 1041, 1062, 1108,  933,  874, 1764, 1021, 1033, 1048,
     1764, 1764, 1042, 1055, 1057, 1764, 1066, 1077, 1078,  930,
     1131, 1135, 1081, 1084, 1127, 1764, 1764, 1764, 1080, 1129,
     1764, 1141, 1147, 1148, 1018, 1167, 1173, 1163, 1182, 1187,
     1183, 1189, 1204, 1218, 1227, 1191, 1205, 1226, 1209, 1240,

     1246, 1247, 1245, 1121, 1260, 1265, 1144, 1764, 1266, 1263,
     1294, 1229, 1282, 1296, 1764, 1289, 1298, 1313, 1309, 1308,
     1230, 1359, 1764, 1764, 1764, 1315, 1311, 1286, 1337, 1764,
      563, 1361, 1333, 1362, 1363, 1390, 1376, 1351, 1392, 1764,
     1764, 1398, 1399, 1404, 1410, 1412, 1418, 1416, 1426, 1444,
     1452, 1450, 1461, 1427, 1465, 1395, 1467, 1445, 1473, 1491,
     1457, 1475, 1332, 1496, 1479, 1764, 1500, 1497, 1764, 1525,
     1519, 1571, 1764, 1527, 1501, 1531, 1764,  947, 1434, 1557,
     1490, 1569, 1764, 1764, 1764, 1536, 1570, 1547, 1554, 1582,
     1606, 1593, 1607, 1587, 1764, 1612, 1601, 1602, 1618, 1588,

     1631, 1764, 1338, 1623, 1605, 1764, 1624, 1649, 1658, 1659,
     1663, 1667, 1671, 1764, 1651, 1669, 1695, 1685, 1764, 1673,
     1764, 1755,   74, 1757, 1759, 1761
    } ;

static const flex_int16_t yy_def[427] =
    {   0,
      421,    1,  422,  422,  422,  422,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  423,  423,
      423,  423,  423,   42,   42,  423,  423,  423,  423,   42,
      423,  423,  423,  423,  423,  423,  423,  423,  421,  421,
      421,  421,  421,  421,  421,  424,  421,  425,  421,  426,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  424,  421,  425,  421,  426,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  423,  423,  423,  423,  423,
      423,  423,  423,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  423,  423,  423,
      423,  421,  421,  421,  421,  423,  423,  421,  421,  423,
        0,  421,  421,  421,  421,  421
    } ;

static const flex_int16_t yy_nxt[1825] =
    {   0,
        8,    9,   10,   11,   12,   13,    8,   14,   15,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,    8,   27,    8,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,    8,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   46,   46,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   46,   59,
       61,   61,   63,   63,   76,   62,   62,   64,   64,   69,
       71,   73,   72,   70,   74,  116,   77,   91,   80,   90,
       71,   94,   72,   81,   92,   83,   76,   84,  159,   78,
      170,   86,  160,   95,   73,  169,   87,   74,   77,   91,

       80,   88,   90,   94,   75,   76,   81,   92,   83,   96,
       84,   90,   78,   86,   97,   82,   95,   93,  102,   87,
       85,   79,   99,  105,   88,   95,   94,  106,   89,  107,
      112,   96,  100,  103,  202,  108,  111,   97,  113,  114,
      102,  162,  163,  109,   99,  105,   98,   73,  167,  106,
       74,  107,  112,  162,  163,  100,  103,  202,  108,  111,
      113,  114,  101,  104,  105,  202,  109,  110,  106,  111,
      117,   76,   77,  118,  421,  112,  115,  421,  179,  421,
       75,   83,  421,   84,  421,   78,  421,  421,  172,  165,
      161,   80,   86,  119,  120,  421,   81,   87,  421,  176,

      158,  179,   88,  179,  124,  421,  125,  421,  121,  170,
       90,  172,   76,  122,  126,  169,   85,   79,  172,  123,
      127,   96,  176,   94,   91,  128,   97,  116,   82,   89,
      167,   92,  176,  129,  421,  421,  421,   95,  421,  421,
       99,  102,   90,  134,  105,  132,  130,  421,  178,  135,
      100,  165,  421,  421,  131,  421,  103,   65,   98,  106,
      133,  171,  136,  138,   93,  161,  140,  421,   94,   95,
      421,  178,  111,  137,  178,  421,  158,  112,   68,  139,
      101,  141,  107,  171,   67,  105,  104,  421,  108,  421,
      421,  174,  421,  113,  114,  145,  109,   66,  421,  146,

      106,  421,  186,  171,  142,  111,  171,  182,  159,   65,
      188,  143,  160,  174,  421,  147,  148,  421,  172,  144,
      110,  421,  112,  175,  421,  186,  421,  421,  171,  182,
      174,  115,  149,  188,  421,  186,  150,  151,  188,  152,
      153,  172,   83,  181,  154,  155,  175,  156,  173,  182,
       88,  176,  175,  109,  149,  175,  178,  179,  150,  151,
      184,  152,  153,  185,  421,   83,  181,  154,  155,  194,
      156,  191,  181,   88,  176,  182,  109,  157,  175,  178,
      179,  189,  180,  184,  177,  184,  185,  186,  181,  421,
      185,  194,  190,  185,  191,  184,  192,  182,  191,  195,

      421,  201,  421,  189,  194,  192,  191,  421,  184,  200,
      186,  181,  194,  185,  190,  195,  421,  183,  197,  192,
      187,  191,  195,  201,  192,  189,  194,  204,  192,  201,
      198,  195,  200,  193,  190,  205,  207,  200,  195,  202,
      197,  206,  201,  421,  421,  206,  421,  196,  421,  421,
      204,  201,  421,  198,  207,  204,  421,  171,  205,  207,
      421,  199,  202,  206,  207,  205,  421,  206,  421,  421,
      203,  172,  176,  421,  174,  421,  421,  207,  206,  209,
      421,  421,  208,  421,  421,  175,  421,  421,  421,  421,
      421,  421,  181,  178,  210,  213,  211,  421,  182,  171,

      185,  172,  421,  421,  421,  176,  421,  421,  212,  186,
      421,  179,  421,  174,  175,  216,  214,  421,  421,  178,
      217,  181,  184,  219,  421,  421,  421,  421,  421,  421,
      185,  188,  220,  189,  215,  421,  179,  421,  421,  190,
      182,  191,  186,  421,  421,  218,  421,  421,  421,  421,
      421,  421,  421,  421,  221,  222,  194,  184,  421,  188,
      421,  223,  197,  421,  224,  192,  421,  421,  421,  421,
      421,  195,  421,  421,  198,  421,  191,  189,  226,  201,
      377,  190,  421,  421,  228,  421,  421,  421,  225,  421,
      421,  200,  421,  192,  227,  421,  242,  229,  421,  194,

      421,  231,  377,  195,  421,  199,  202,  421,  421,  421,
      204,  421,  205,  204,  230,  421,  421,  206,  242,  200,
      201,  421,  377,  421,  421,  421,  421,  266,  207,  232,
      189,  194,  421,  204,  421,  234,  233,  202,  243,  235,
      255,  204,  205,  197,  205,  175,  421,  174,  421,  421,
      266,  236,  189,  194,  206,  198,  207,  201,  200,  266,
      255,  206,  255,  421,  240,  197,  256,  205,  175,  174,
      195,  207,  172,  178,  237,  257,  421,  421,  198,  201,
      421,  200,  255,  206,  258,  255,  238,  240,  256,  257,
      421,  421,  260,  195,  207,  172,  178,  257,  239,  241,

      190,  258,  246,  256,  273,  255,  260,  258,  263,  176,
      421,  257,  185,  258,  244,  260,  257,  179,  421,  261,
      421,  421,  190,  421,  258,  260,  421,  273,  421,  260,
      259,  263,  176,  263,  421,  185,  273,  244,  421,  260,
      179,  261,  245,  189,  247,  248,  201,  261,  174,  262,
      206,  264,  240,  421,  249,  195,  250,  251,  252,  253,
      261,  178,  179,  421,  267,  189,  247,  248,  201,  261,
      174,  262,  206,  264,  264,  240,  262,  249,  195,  250,
      251,  252,  253,  268,  178,  179,  267,  254,  261,  421,
      262,  274,  263,  280,  264,  421,  264,  266,  262,  269,

      269,  276,  421,  270,  270,  267,  268,  268,  421,  274,
      421,  277,  421,  274,  279,  263,  280,  265,  273,  268,
      266,  269,  269,  281,  276,  270,  270,  277,  280,  266,
      268,  274,  274,  277,  276,  276,  279,  281,  421,  421,
      280,  273,  271,  272,  421,  281,  421,  421,  258,  277,
      275,  279,  277,  421,  255,  421,  421,  262,  276,  281,
      256,  281,  257,  280,  421,  421,  421,  421,  278,  421,
      421,  286,  261,  421,  421,  282,  283,  258,  260,  262,
      421,  421,  284,  421,  285,  262,  421,  421,  421,  266,
      421,  421,  264,  421,  288,  263,  421,  256,  262,  255,

      324,  287,  421,  257,  421,  421,  421,  289,  267,  421,
      421,  260,  292,  261,  291,  421,  421,  421,  290,  421,
      263,  266,  421,  324,  421,  421,  262,  421,  268,  421,
      293,  421,  269,  324,  421,  264,  270,  421,  273,  421,
      421,  421,  421,  421,  276,  421,  421,  421,  421,  267,
      421,  294,  274,  421,  295,  421,  421,  421,  296,  333,
      421,  297,  279,  421,  268,  421,  421,  299,  323,  421,
      273,  421,  277,  281,  298,  271,  421,  276,  421,  405,
      421,  421,  333,  421,  301,  280,  421,  421,  279,  333,
      421,  323,  323,  274,  300,  303,  304,  421,  421,  279,

      274,  268,  405,  421,  256,  280,  405,  276,  302,  273,
      279,  281,  421,  277,  262,  421,  421,  281,  304,  421,
      280,  255,  274,  269,  268,  279,  256,  270,  280,  421,
      276,  313,  273,  421,  260,  266,  262,  305,  258,  281,
      307,  306,  263,  255,  421,  269,  268,  421,  264,  270,
      273,  421,  325,  313,  255,  308,  327,  260,  266,  315,
      421,  258,  258,  421,  325,  263,  310,  309,  421,  268,
      264,  327,  313,  273,  263,  325,  255,  421,  327,  326,
      325,  315,  311,  281,  279,  258,  328,  325,  328,  266,
      330,  312,  325,  327,  421,  331,  332,  263,  338,  314,

      315,  327,  326,  421,  340,  281,  279,  326,  421,  328,
      337,  328,  266,  330,  328,  421,  329,  331,  332,  421,
      338,  316,  255,  421,  317,  330,  318,  340,  270,  281,
      319,  268,  280,  337,  320,  321,  331,  332,  258,  340,
      337,  338,  263,  338,  255,  330,  317,  341,  318,  332,
      270,  281,  319,  335,  268,  280,  337,  320,  321,  341,
      333,  258,  341,  338,  333,  263,  421,  322,  330,  341,
      421,  332,  421,  421,  324,  335,  421,  421,  421,  337,
      330,  341,  323,  333,  341,  421,  339,  333,  341,  421,
      334,  421,  421,  421,  336,  421,  421,  343,  325,  421,

      341,  327,  421,  341,  326,  342,  323,  324,  421,  421,
      421,  421,  421,  421,  328,  421,  421,  421,  421,  421,
      333,  344,  421,  346,  421,  421,  325,  345,  330,  421,
      421,  421,  326,  421,  337,  421,  331,  347,  421,  421,
      338,  421,  328,  351,  421,  332,  327,  421,  421,  421,
      333,  348,  421,  421,  421,  421,  421,  352,  349,  337,
      362,  421,  353,  330,  337,  341,  421,  350,  421,  421,
      340,  421,  421,  421,  421,  421,  421,  331,  331,  338,
      327,  332,  337,  362,  330,  338,  332,  355,  362,  337,
      421,  324,  333,  354,  337,  421,  338,  358,  323,  421,

      331,  338,  327,  332,  421,  340,  341,  330,  375,  421,
      327,  421,  331,  340,  324,  333,  332,  337,  338,  356,
      358,  323,  360,  337,  357,  359,  421,  338,  421,  328,
      375,  323,  327,  340,  331,  324,  340,  330,  332,  326,
      374,  338,  373,  421,  421,  375,  337,  379,  340,  338,
      421,  421,  328,  361,  323,  363,  340,  364,  324,  375,
      330,  374,  326,  374,  414,  373,  374,  326,  366,  379,
      374,  421,  365,  367,  373,  421,  379,  368,  378,  378,
      381,  375,  384,  369,  374,  324,  421,  414,  370,  374,
      371,  374,  379,  383,  323,  367,  376,  414,  379,  368,

      378,  378,  381,  421,  379,  384,  369,  381,  324,  383,
      384,  370,  377,  371,  421,  383,  421,  323,  372,  421,
      378,  380,  381,  384,  421,  421,  379,  421,  421,  381,
      421,  383,  421,  421,  377,  383,  421,  373,  421,  421,
      375,  374,  421,  377,  421,  421,  384,  421,  421,  382,
      421,  385,  421,  421,  377,  421,  421,  421,  421,  406,
      386,  378,  388,  421,  387,  389,  379,  383,  421,  373,
      421,  374,  373,  421,  395,  421,  421,  375,  421,  421,
      421,  421,  406,  390,  383,  377,  421,  421,  391,  392,
      421,  421,  384,  406,  421,  373,  395,  375,  384,  421,

      373,  421,  374,  378,  373,  379,  383,  421,  378,  383,
      384,  379,  421,  378,  381,  393,  395,  421,  375,  375,
      384,  384,  405,  373,  421,  374,  385,  379,  403,  374,
      378,  384,  394,  384,  375,  378,  381,  421,  384,  379,
      375,  375,  383,  421,  402,  405,  373,  421,  402,  405,
      380,  403,  374,  421,  384,  396,  381,  421,  403,  397,
      403,  379,  421,  375,  383,  421,  402,  421,  421,  373,
      402,  421,  421,  421,  403,  421,  421,  421,  399,  421,
      421,  403,  406,  421,  398,  379,  402,  402,  400,  405,
      404,  421,  421,  375,  406,  421,  421,  409,  373,  421,

      374,  405,  384,  421,  402,  406,  403,  379,  421,  408,
      400,  421,  405,  421,  405,  375,  407,  406,  402,  421,
      405,  373,  421,  374,  405,  384,  402,  406,  407,  402,
      401,  406,  421,  421,  415,  421,  421,  410,  421,  403,
      402,  405,  421,  405,  405,  403,  402,  405,  402,  414,
      406,  421,  421,  415,  411,  421,  406,  415,  403,  421,
      402,  406,  403,  405,  415,  406,  421,  405,  403,  419,
      402,  412,  414,  421,  421,  421,  415,  403,  421,  406,
      421,  403,  414,  415,  414,  421,  405,  421,  415,  421,
      413,  419,  421,  414,  421,  421,  415,  414,  421,  421,

      415,  421,  421,  419,  421,  421,  421,  416,  421,  421,
      419,  417,  421,  419,  421,  421,  414,  414,  415,  415,
      414,  421,  421,  415,  421,  419,  418,  421,  421,  421,
      418,  421,  421,  421,  421,  420,  421,  421,  421,  421,
      421,  421,  421,  421,  419,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  419,   60,   60,  164,  164,  166,
      166,  168,  168,    7,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421
    } ;

static const flex_int16_t yy_chk[1825] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,   21,    3,    4,    5,    6,   17,
       18,   20,   18,   17,   20,  423,   22,   27,   23,   26,
       72,   28,   72,   23,   27,   24,   21,   24,   62,   22,
      170,   25,   62,   29,   20,  168,   25,   20,   22,   27,

       23,   25,   26,   28,   20,   21,   23,   27,   24,   30,
       24,   26,   22,   25,   30,   23,   29,   27,   32,   25,
       24,   22,   31,   33,   25,   29,   28,   34,   25,   35,
       37,   30,   31,   32,  109,   35,   36,   30,   38,   38,
       32,   64,   64,   35,   31,   33,   30,   39,  166,   34,
       39,   35,   37,  163,  163,   31,   32,  109,   35,   36,
       38,   38,   31,   32,   33,  109,   35,   35,   34,   36,
       39,   40,   41,   39,   46,   37,   38,   46,   81,   40,
       39,   43,   40,   43,   41,   41,   43,   41,   74,  164,
      161,   42,   44,   40,   41,   42,   42,   44,   42,   78,

      158,   81,   44,   81,   43,   45,   43,   46,   41,   71,
       45,   74,   40,   42,   44,   70,   43,   41,   74,   42,
       44,   50,   78,   48,   47,   44,   50,   45,   42,   44,
       68,   47,   78,   45,   47,   48,   49,   49,   48,   49,
       51,   52,   45,   50,   53,   48,   47,   51,   80,   50,
       51,   66,   53,   52,   47,   53,   52,   65,   50,   54,
       49,   73,   51,   52,   47,   63,   53,   54,   48,   49,
       54,   80,   56,   51,   80,   56,   61,   57,   14,   52,
       51,   54,   55,   73,   13,   53,   52,   55,   55,   57,
       55,   76,   57,   58,   58,   56,   55,   12,   58,   57,

       54,   58,   88,   73,   55,   56,   75,   84,  159,    9,
       90,   55,  159,   76,    7,   58,   58,    0,   75,   55,
       55,    0,   57,   77,    0,   88,    0,    0,   75,   84,
       76,   58,   59,   90,    0,   88,   59,   59,   90,   59,
       59,   75,   59,   83,   59,   59,   77,   59,   75,   84,
       59,   79,   77,   59,   59,   79,   82,   82,   59,   59,
       86,   59,   59,   87,    0,   59,   83,   59,   59,  102,
       59,   96,   83,   59,   79,   85,   59,   59,   79,   82,
       82,   94,   82,   86,   79,   89,   87,   89,   85,    0,
       89,  102,   95,   87,   96,   86,   97,   85,   98,  103,

        0,  107,    0,   94,  104,   98,   96,    0,   89,  106,
       89,   85,  102,   89,   95,  104,    0,   85,  105,   97,
       89,   98,  103,  107,   97,   94,  104,  111,   98,  110,
      105,  103,  106,   98,   95,  112,  114,  106,  104,  110,
      105,  113,  107,  116,    0,  115,  116,  104,    0,    0,
      111,  110,    0,  105,  115,  111,    0,  117,  112,  114,
        0,  105,  110,  113,  114,  112,  117,  115,  118,  117,
      110,  118,  121,    0,  119,  121,  116,  115,  113,  117,
      119,  120,  115,  119,  120,  120,  122,    0,  124,  122,
        0,  124,  124,  122,  118,  121,  119,  127,  125,  117,

      127,  118,    0,  123,    0,  121,  123,  125,  120,  128,
      125,  123,  128,  119,  120,  124,  122,    0,    0,  122,
      125,  124,  126,  127,  126,  130,  129,  126,  130,  129,
      127,  129,  128,  132,  123,  131,  123,    0,  131,  133,
      125,  134,  128,  134,  132,  126,  134,  132,  133,  136,
      137,  133,  136,  137,  129,  132,  138,  126,  130,  129,
      135,  133,  140,  135,  134,  135,  138,    0,  131,  138,
      139,  139,  140,  139,  140,  140,  134,  132,  138,  142,
      331,  133,  136,  137,  140,    0,  141,  142,  135,  141,
      142,  141,  143,  135,  139,  143,  154,  140,    0,  138,

        0,  142,  331,  139,  144,  140,  144,  144,  145,  146,
      154,  145,  146,  145,  141,    0,    0,  147,  154,  141,
      142,  147,  331,  148,  147,  143,  148,  188,  148,  144,
      149,  149,    0,  154,    0,  146,  145,  144,  154,  147,
      172,  145,  146,  150,  149,  149,    0,  150,    0,    0,
      188,  148,  149,  149,  147,  150,  148,  152,  150,  188,
      173,  152,  172,    0,  153,  150,  174,  149,  149,  150,
      156,  153,  156,  153,  149,  175,    0,  209,  150,  152,
      209,  150,  173,  152,  176,  172,  150,  153,  174,  177,
        0,    0,  179,  156,  153,  156,  153,  175,  152,  153,

      155,  177,  156,  174,  197,  173,  180,  176,  185,  155,
      209,  177,  155,  176,  155,  179,  175,  155,    0,  181,
      214,    0,  155,  214,  177,  179,    0,  197,    0,  180,
      177,  185,  155,  185,    0,  155,  197,  155,    0,  180,
      155,  181,  155,  157,  157,  157,  157,  183,  157,  184,
      157,  186,  157,  214,  157,  157,  157,  157,  157,  157,
      181,  157,  157,    0,  189,  157,  157,  157,  157,  183,
      157,  184,  157,  186,  187,  157,  187,  157,  157,  157,
      157,  157,  157,  194,  157,  157,  189,  157,  183,    0,
      184,  198,  187,  206,  186,    0,  187,  244,  187,  195,

      196,  201,    0,  195,  196,  189,  194,  196,    0,  199,
        0,  202,    0,  198,  204,  187,  206,  187,  199,  194,
      244,  195,  196,  207,  201,  195,  196,  203,  206,  244,
      196,  199,  198,  202,  201,  203,  204,  208,    0,    0,
      208,  199,  195,  196,  213,  207,    0,  213,  213,  203,
      199,  204,  202,  217,  210,    0,  217,  240,  203,  208,
      211,  207,  212,  208,  211,    0,  210,  211,  203,  210,
      212,  213,  216,  212,    0,  208,  210,  213,  215,  240,
      216,  215,  211,  216,  212,  218,  217,  219,  221,  221,
      219,  221,  220,  218,  216,  219,  218,  211,  240,  210,

      256,  215,  220,  212,    0,  220,  223,  218,  222,  223,
        0,  215,  221,  216,  220,    0,  222,    0,  219,  222,
      219,  221,  224,  256,  225,  224,  218,  225,  226,    0,
      222,  226,  227,  256,  226,  220,  227,  228,  228,  223,
      228,    0,  227,  230,  231,  227,  230,  231,    0,  222,
        0,  226,  229,  234,  227,  224,  234,  225,  227,  270,
      229,  228,  233,  229,  226,    0,  233,  231,  255,  233,
      228,    0,  232,  236,  229,  227,  230,  231,  236,  378,
      232,  236,  270,  232,  233,  235,  234,  235,  243,  270,
      235,  255,  255,  229,  232,  236,  237,    0,    0,  233,

      238,  237,  378,    0,  238,  239,  378,  239,  235,  238,
      243,  236,    0,  232,  241,    0,    0,  241,  237,    0,
      235,  246,  238,  246,  237,  243,  238,  246,  239,    0,
      239,  250,  238,    0,  245,  245,  241,  237,  245,  241,
      239,  238,  245,  246,  285,  246,  247,  285,  249,  246,
      247,    0,  258,  250,  251,  241,  263,  245,  245,  252,
        0,  245,  249,    0,  259,  245,  246,  245,    0,  247,
      249,  265,  250,  247,  251,  258,  251,  285,  263,  260,
      258,  252,  247,  253,  253,  249,  264,  259,  265,  253,
      267,  249,  259,  265,    0,  268,  269,  251,  274,  251,

      252,  263,  260,    0,  279,  253,  253,  260,    0,  264,
      273,  265,  253,  267,  264,    0,  265,  268,  269,    0,
      274,  253,  254,    0,  254,  267,  254,  279,  254,  254,
      254,  254,  254,  273,  254,  254,  268,  269,  254,  279,
      273,  275,  254,  274,  254,  304,  254,  280,  254,  271,
      254,  254,  254,  272,  254,  254,  275,  254,  254,  282,
      271,  254,  307,  275,  272,  254,    0,  254,  304,  280,
        0,  271,    0,  283,  284,  272,  283,  284,    0,  275,
      304,  282,  283,  271,  307,    0,  275,  272,  280,  288,
      271,    0,  288,  286,  272,    0,  286,  284,  286,  287,

      282,  290,  287,  307,  287,  283,  283,  284,  289,  291,
        0,  289,  291,  290,  291,  292,  290,  296,  292,    0,
      296,  286,  288,  290,    0,    0,  286,  287,  293,    0,
      293,  297,  287,  293,  297,  299,  294,  291,  299,    0,
      298,  289,  291,  296,  294,  295,  290,  294,  292,    0,
      296,  293,  298,  295,    0,  298,  295,  297,  294,  321,
      312,    0,  298,  293,  297,  302,  300,  295,  299,  300,
      301,  303,  301,  302,  303,  301,  302,  294,  305,  306,
      309,  310,  321,  312,  305,  298,  295,  302,  312,  321,
        0,  306,  310,  301,  306,    0,  313,  309,  310,  300,

      305,  306,  309,  310,  303,  301,  302,  305,  328,    0,
      314,    0,  311,  316,  306,  310,  317,  306,  313,  305,
      309,  310,  310,  311,  306,  309,    0,  318,    0,  317,
      328,  314,  314,  319,  311,  319,  316,  318,  317,  320,
      327,  313,  326,    0,    0,  328,  311,  333,  316,  318,
        0,    0,  317,  311,  314,  314,  319,  317,  319,  329,
      318,  363,  320,  327,  403,  326,  329,  320,  319,  333,
      327,    0,  318,  322,  326,    0,  334,  322,  332,  334,
      335,  329,  338,  322,  363,  322,    0,  403,  322,  329,
      322,  363,  333,  337,  322,  322,  329,  403,  334,  322,

      332,  334,  335,    0,  336,  338,  322,  336,  322,  339,
      338,  322,  356,  322,    0,  337,    0,  322,  322,    0,
      332,  334,  335,  339,  342,  343,  336,  342,  343,  336,
      344,  339,    0,  344,  356,  337,  345,  345,  346,  345,
      347,  346,  348,  349,  347,  348,  339,  347,    0,  336,
        0,  339,  349,  354,  356,  349,  354,  342,  343,  379,
      345,  350,  347,  344,  346,  349,  351,  352,    0,  345,
      350,  346,  358,  350,  361,  348,  352,  347,  351,  352,
        0,  351,  379,  350,  357,  349,  354,  353,  351,  352,
      353,  355,  353,  379,  355,  358,  361,  362,  357,    0,

      359,    0,  359,  350,  358,  360,  357,    0,  360,  352,
      365,  351,    0,  364,  368,  353,  361,    0,  364,  362,
      353,  357,  381,  359,  355,  359,  357,  360,  375,  367,
      360,  367,  359,  365,  362,  364,  368,    0,  365,  370,
      364,  371,  370,    0,  374,  381,  371,    0,  376,  381,
      360,  375,  367,    0,  367,  364,  368,    0,  376,  367,
      375,  370,  386,  371,  370,  386,  374,    0,    0,  371,
      376,    0,    0,  388,  388,    0,  388,    0,  371,    0,
      389,  376,  380,  389,  370,  372,  374,  387,  372,  380,
      376,    0,    0,  372,  382,  386,  387,  388,  372,  387,

      372,  382,  372,    0,  394,  380,  388,  372,  390,  387,
      372,  390,  380,  389,  390,  372,  380,  382,  397,  392,
      400,  372,  392,  372,  382,  372,  394,  398,  382,  387,
      372,  391,  391,  393,  405,  391,  393,  390,    0,  396,
      397,  390,    0,  400,  396,  399,  394,  400,  401,  404,
      398,    0,  392,  407,  391,    0,  401,  405,  401,    0,
      397,  398,  396,  401,  405,  391,  393,  396,  399,  415,
      401,  396,  404,    0,    0,  408,  407,  399,  408,  401,
        0,  401,  404,  407,  409,  410,  401,  409,  410,  411,
      401,  415,  411,  412,    0,  416,  412,  413,  416,  420,

      413,    0,  420,  418,    0,    0,    0,  409,  408,    0,
      415,  410,    0,  417,    0,    0,  412,  409,  410,  412,
      413,  417,  411,  413,  417,  418,  412,    0,  416,    0,
      413,    0,  420,    0,    0,  417,    0,    0,    0,    0,
        0,    0,    0,    0,  418,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  417,  422,  422,  424,  424,  425,
      425,  426,  426,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "PascalDSL.l"
#line 2 "PascalDSL.l"
# include "common.h"
# include "PascalDSL.tab.h"

char buffer[200];
typedef void (*addParserErrorText)(char* message);
static addParserErrorText m_addParserErrorText;

void* addTextPtr;
#line 1251 "lex.pascal.c"

#line 1253 "lex.pascal.c"

#define INITIAL 0
#define Comment1 1
#define Comment2 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 43 "PascalDSL.l"


#line 1475 "lex.pascal.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 422 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1764 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "PascalDSL.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 46 "PascalDSL.l"
{ /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "PascalDSL.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 49 "PascalDSL.l"
{ /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "PascalDSL.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 52 "PascalDSL.l"
{ /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "PascalDSL.l"
{             BEGIN(Comment1); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 55 "PascalDSL.l"
{ ++yylineno;      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "PascalDSL.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "PascalDSL.l"
{             BEGIN(Comment2); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 59 "PascalDSL.l"
{ ++yylineno;      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "PascalDSL.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "PascalDSL.l"
{ /* empty */ }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 63 "PascalDSL.l"
{ ++yylineno; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "PascalDSL.l"
{ return TOK_PAS_AND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "PascalDSL.l"
{ return TOK_PAS_ARRAY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "PascalDSL.l"
{ return TOK_PAS_BEGIN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "PascalDSL.l"
{ return TOK_PAS_CASE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "PascalDSL.l"
{ return TOK_PAS_CONST; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "PascalDSL.l"
{ return TOK_PAS_DIV; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "PascalDSL.l"
{ return TOK_PAS_DO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "PascalDSL.l"
{ return TOK_PAS_DOWNTO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "PascalDSL.l"
{ return TOK_PAS_ELSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "PascalDSL.l"
{ return TOK_PAS_END; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "PascalDSL.l"
{ return TOK_PAS_FILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "PascalDSL.l"
{ return TOK_PAS_FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "PascalDSL.l"
{ return TOK_PAS_FORWARD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "PascalDSL.l"
{ return TOK_PAS_FUNCTION; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "PascalDSL.l"
{ return TOK_PAS_GOTO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "PascalDSL.l"
{ return TOK_PAS_IF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "PascalDSL.l"
{ return TOK_PAS_IN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "PascalDSL.l"
{ return TOK_PAS_LABEL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "PascalDSL.l"
{ return TOK_PAS_MOD; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "PascalDSL.l"
{ return TOK_PAS_NIL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "PascalDSL.l"
{ return TOK_PAS_NOT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "PascalDSL.l"
{ return TOK_PAS_OF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "PascalDSL.l"
{ return TOK_PAS_OR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "PascalDSL.l"
{ return TOK_PAS_PACKED; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "PascalDSL.l"
{ return TOK_PAS_PROCEDURE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "PascalDSL.l"
{ MessageBox(0,"oooppp","test",0); return TOK_PAS_PROGRAM; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "PascalDSL.l"
{ return TOK_PAS_RECORD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "PascalDSL.l"
{ return TOK_PAS_REPEAT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "PascalDSL.l"
{ return TOK_PAS_SET; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "PascalDSL.l"
{ return TOK_PAS_THEN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "PascalDSL.l"
{ return TOK_PAS_TO; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "PascalDSL.l"
{ return TOK_PAS_TYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "PascalDSL.l"
{ return TOK_PAS_UNTIL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "PascalDSL.l"
{ return TOK_PAS_VAR; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "PascalDSL.l"
{ return TOK_PAS_WHILE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "PascalDSL.l"
{ return TOK_PAS_WITH; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "PascalDSL.l"
{ return TOK_PAS_ID;  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "PascalDSL.l"
{
  sprintf(buffer, "An integer: %s (%d)\n", yytext,
  atoi( yytext ) );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "PascalDSL.l"
{
  sprintf(buffer, "A float: %s (%g)\n", yytext,
  atof( yytext ) );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 117 "PascalDSL.l"
{ return ';'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 118 "PascalDSL.l"
{ return '.'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 120 "PascalDSL.l"
{
  return
  sprintf( buffer, "An operator: %s\n", yytext );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "PascalDSL.l"
{
  sprintf( buffer, "Unrecognized character: %s\n", yytext );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 131 "PascalDSL.l"
ECHO;
	YY_BREAK
#line 1843 "lex.pascal.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
case YY_STATE_EOF(Comment2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 422 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 422 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 421);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 131 "PascalDSL.l"


void yy_pascal_lex_parser_error(void (*func)(char*)) {
  m_addParserErrorText = func;
}

int pascalwrap(void) { return 1; }

void pascalerror(char* message)
{
  char* bu;
  bu = (char*) malloc(strlen(message)+42);
  strcpy(bu,"error: ");
  strcat(bu,message);

  m_addParserErrorText(bu);
}

BOOL yy_pascal_lex_main(char* filename)
{
  yyin = fopen(filename,"r");
  if (!yyin) {
    sprintf(buffer, "could not open file: %s", filename);
    m_addParserErrorText(buffer);
    return false;
  }

  //yylex();
  pascalparse();
  fclose(yyin);

  return true;
}

int yy_pascal_lex_getlines(void) { return yylineno-1; }

void __declspec(dllexport) yy_pascal_lex_parser_error(void (*func)(char*));
int  __declspec(dllexport) yy_pascal_lex_getlines(void);

BOOL __declspec(dllexport) yy_pascal_lex_main(char* filename);


