
#line 2 "lex.pascal.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pascal_create_buffer
#define yy_delete_buffer pascal_delete_buffer
#define yy_scan_buffer pascal_scan_buffer
#define yy_scan_string pascal_scan_string
#define yy_scan_bytes pascal_scan_bytes
#define yy_init_buffer pascal_init_buffer
#define yy_flush_buffer pascal_flush_buffer
#define yy_load_buffer_state pascal_load_buffer_state
#define yy_switch_to_buffer pascal_switch_to_buffer
#define yypush_buffer_state pascalpush_buffer_state
#define yypop_buffer_state pascalpop_buffer_state
#define yyensure_buffer_stack pascalensure_buffer_stack
#define yy_flex_debug pascal_flex_debug
#define yyin pascalin
#define yyleng pascalleng
#define yylex pascallex
#define yylineno pascallineno
#define yyout pascalout
#define yyrestart pascalrestart
#define yytext pascaltext
#define yywrap pascalwrap
#define yyalloc pascalalloc
#define yyrealloc pascalrealloc
#define yyfree pascalfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define pascal_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer pascal_create_buffer
#endif

#ifdef yy_delete_buffer
#define pascal_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer pascal_delete_buffer
#endif

#ifdef yy_scan_buffer
#define pascal_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer pascal_scan_buffer
#endif

#ifdef yy_scan_string
#define pascal_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string pascal_scan_string
#endif

#ifdef yy_scan_bytes
#define pascal_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes pascal_scan_bytes
#endif

#ifdef yy_init_buffer
#define pascal_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer pascal_init_buffer
#endif

#ifdef yy_flush_buffer
#define pascal_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer pascal_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define pascal_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state pascal_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define pascal_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer pascal_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define pascalpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state pascalpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define pascalpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state pascalpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define pascalensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack pascalensure_buffer_stack
#endif

#ifdef yylex
#define pascallex_ALREADY_DEFINED
#else
#define yylex pascallex
#endif

#ifdef yyrestart
#define pascalrestart_ALREADY_DEFINED
#else
#define yyrestart pascalrestart
#endif

#ifdef yylex_init
#define pascallex_init_ALREADY_DEFINED
#else
#define yylex_init pascallex_init
#endif

#ifdef yylex_init_extra
#define pascallex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra pascallex_init_extra
#endif

#ifdef yylex_destroy
#define pascallex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy pascallex_destroy
#endif

#ifdef yyget_debug
#define pascalget_debug_ALREADY_DEFINED
#else
#define yyget_debug pascalget_debug
#endif

#ifdef yyset_debug
#define pascalset_debug_ALREADY_DEFINED
#else
#define yyset_debug pascalset_debug
#endif

#ifdef yyget_extra
#define pascalget_extra_ALREADY_DEFINED
#else
#define yyget_extra pascalget_extra
#endif

#ifdef yyset_extra
#define pascalset_extra_ALREADY_DEFINED
#else
#define yyset_extra pascalset_extra
#endif

#ifdef yyget_in
#define pascalget_in_ALREADY_DEFINED
#else
#define yyget_in pascalget_in
#endif

#ifdef yyset_in
#define pascalset_in_ALREADY_DEFINED
#else
#define yyset_in pascalset_in
#endif

#ifdef yyget_out
#define pascalget_out_ALREADY_DEFINED
#else
#define yyget_out pascalget_out
#endif

#ifdef yyset_out
#define pascalset_out_ALREADY_DEFINED
#else
#define yyset_out pascalset_out
#endif

#ifdef yyget_leng
#define pascalget_leng_ALREADY_DEFINED
#else
#define yyget_leng pascalget_leng
#endif

#ifdef yyget_text
#define pascalget_text_ALREADY_DEFINED
#else
#define yyget_text pascalget_text
#endif

#ifdef yyget_lineno
#define pascalget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno pascalget_lineno
#endif

#ifdef yyset_lineno
#define pascalset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno pascalset_lineno
#endif

#ifdef yywrap
#define pascalwrap_ALREADY_DEFINED
#else
#define yywrap pascalwrap
#endif

#ifdef yyalloc
#define pascalalloc_ALREADY_DEFINED
#else
#define yyalloc pascalalloc
#endif

#ifdef yyrealloc
#define pascalrealloc_ALREADY_DEFINED
#else
#define yyrealloc pascalrealloc
#endif

#ifdef yyfree
#define pascalfree_ALREADY_DEFINED
#else
#define yyfree pascalfree
#endif

#ifdef yytext
#define pascaltext_ALREADY_DEFINED
#else
#define yytext pascaltext
#endif

#ifdef yyleng
#define pascalleng_ALREADY_DEFINED
#else
#define yyleng pascalleng
#endif

#ifdef yyin
#define pascalin_ALREADY_DEFINED
#else
#define yyin pascalin
#endif

#ifdef yyout
#define pascalout_ALREADY_DEFINED
#else
#define yyout pascalout
#endif

#ifdef yy_flex_debug
#define pascal_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug pascal_flex_debug
#endif

#ifdef yylineno
#define pascallineno_ALREADY_DEFINED
#else
#define yylineno pascallineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[448] =
    {   0,
       13,   13,    8,    8,   11,   11,   61,   59,   13,   14,
       14,   59,   59,   58,   58,   57,   58,   54,   56,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   14,   60,
        8,   60,   11,   60,   13,    3,   10,    5,    7,    1,
       55,   54,    0,    0,    0,    0,    0,    0,    0,    0,
       21,   21,    0,    0,    0,    0,    0,    0,    0,    0,
       30,   31,   30,    0,    0,    0,    0,    0,    0,    0,

       37,   38,   37,    0,    0,    0,    0,    0,    0,   46,
        0,   46,    0,    0,    0,    0,    0,   53,   53,   53,
       53,   53,   53,   53,   21,   53,   53,   53,   53,   53,
       53,   30,   31,   53,   53,   53,   53,   53,   37,   38,
       53,   53,   53,   53,   53,   46,   53,   53,   53,   53,
       53,    0,    0,   30,    0,    0,   31,   21,   38,   21,
        8,    0,    9,   11,   12,    0,    3,    4,    5,    6,
        1,    2,   55,   15,    0,   15,    0,    0,    0,    0,
       20,    0,   20,    0,   24,   24,    0,   26,    0,   26,
        0,    0,    0,    0,   34,   35,   36,   35,    0,    0,

        0,    0,    0,    0,   44,    0,    0,    0,    0,    0,
        0,   50,    0,    0,    0,   15,   53,   53,   53,   53,
       20,   53,   53,   24,   53,   26,   53,   53,   53,   53,
       34,   35,   36,   53,   53,   53,   53,   44,   53,   53,
       53,   53,   50,   53,   53,   50,   44,    0,   35,   20,
       15,   15,   36,   26,    0,    0,   15,    0,    0,    0,
       26,    0,   36,   15,    0,    0,   18,    0,   18,    0,
       23,   25,    0,    0,   25,   29,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   45,   47,   45,
       48,    0,   48,    0,   52,   52,   53,   53,   18,   53,

       53,   23,   25,   53,   53,   29,   53,   53,   53,   53,
       53,   53,   53,   45,   47,   48,   53,   53,   52,   18,
       18,    0,   45,   25,   29,    0,    0,   48,    0,   47,
        0,   18,   29,    0,   18,    0,   45,   29,   18,   16,
       17,   19,    0,    0,    0,    0,   32,    0,   32,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   49,   51,
       16,   17,   19,   53,   53,   53,   32,   53,   53,   53,
       53,   53,   53,   49,   51,   32,   17,   19,   19,   16,
        0,   19,   16,    0,   32,   17,    0,   51,   32,    0,
       19,   16,   22,    0,    0,    0,    0,   39,    0,    0,

        0,   39,   39,   42,   43,   42,   22,   53,   53,   53,
       39,   53,   53,   42,   43,   22,   39,    0,    0,   43,
       42,   22,   39,   22,   27,    0,   27,   33,    0,   41,
       41,   27,   53,   33,   53,   41,    0,   27,   27,   28,
        0,   28,   53,   28,   40,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    5,    1,    6,
        7,    8,    9,    1,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,    1,
        1,    1,    1,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   46,   53,   54,   55,   56,   57,   58,   46,
       59,   46,    1,   60,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[453] =
    {   0,
        0,    0,   58,   59,   60,   61,  272, 1912,  264, 1912,
     1912,  221,  210,  203, 1912, 1912,   62,   60, 1912,   45,
       46,   62,   56,   61,   69,   52,   58,  100,   66,   96,
      108,  112,   91,  111,  118,  107,  116,  136,  152,  156,
      173,  162,  179,  192,  191,  106,  208,  217,  229,  218,
      240,  234,  254,  256,  274,  249,  276,  285,  331, 1912,
      205,   81,  196,   74,  182,  171, 1912,  170, 1912,  167,
      150,  180,  205,  134,  287,  174,  288,  171,  335,  264,
      195,  336,  289,  317,  368,  263,  344,  305,  353,  356,
     1912, 1912, 1912,  376,  382,  386,  387,  375,  377,  385,

     1912, 1912, 1912,  390,  309,  402,  409,  389,  303, 1912,
      405,  435,  428,  422,  432,  411,  436,  440,  467,  459,
      463,  471,  478,  483,  491,  502,  512,  520,  484,  527,
      528,  534,  536,  543,  555,  549,  565,  572,  548,  570,
      584,  589,  604,  615,  609,  599,  608,  631,  621,  650,
      652,  683,  672, 1912,  675,  671,  707,  750,  637,  795,
      152,  127, 1912,  145, 1912,  136,  101, 1912,   93, 1912,
       88, 1912,   70, 1912,  443,  509,  695,  704,  703,  719,
     1912,  706,  715,  710, 1912,  735,  742,  648,  439,  822,
      718,  755,  625,  768, 1912, 1912, 1912, 1912,  560,  845,

      847,  721,  813,  846, 1912,  744,  818,  848,  586,  854,
      868, 1912,  759,  857,  871,  842,  895,  897,  899,  906,
      908,  914,  920,  916,  926,  935,  952,  921,  958,  948,
      957,  962,  967,  976,  994,  998, 1011,  975, 1012, 1026,
     1033,  986,  980, 1034, 1046, 1010, 1056, 1060,  851, 1059,
     1912, 1072, 1063, 1094, 1116, 1087, 1912, 1103, 1038,  911,
     1125, 1064, 1142, 1188,  960, 1086, 1912,  849, 1111, 1117,
     1912, 1912, 1081, 1118, 1124, 1912,  835, 1154, 1215, 1148,
     1185, 1164, 1225, 1228, 1168, 1219, 1234, 1912, 1912, 1912,
     1912, 1132, 1212, 1232, 1912, 1235, 1223, 1240, 1020, 1259,

     1266, 1247, 1272, 1286, 1276, 1282, 1290, 1303, 1318, 1324,
     1314, 1322, 1342, 1295, 1326, 1331, 1341, 1358, 1343, 1279,
     1368, 1377, 1357, 1375, 1404, 1402, 1392, 1364, 1365, 1411,
     1414, 1912, 1398, 1412, 1432, 1415, 1422, 1275, 1478, 1912,
     1912, 1912, 1146, 1426, 1453, 1464, 1912, 1430, 1436,  894,
     1460, 1469, 1503, 1467, 1507, 1494, 1456, 1517, 1912, 1912,
     1472, 1509, 1515, 1523, 1525, 1535, 1529, 1534, 1552, 1563,
     1561, 1578, 1570, 1541, 1577, 1566, 1592, 1571, 1583, 1602,
     1601, 1604, 1556, 1610, 1603, 1912, 1614, 1611, 1912, 1638,
     1631, 1684, 1912, 1648, 1617, 1655, 1621, 1912, 1224, 1660,

     1670, 1435, 1678, 1912, 1912, 1912, 1657, 1683, 1718, 1695,
     1706, 1720, 1730, 1722, 1731, 1723, 1912, 1737, 1741, 1749,
     1702, 1736, 1738, 1792, 1912, 1745, 1757, 1912, 1762, 1912,
     1773, 1784, 1786, 1794, 1800, 1804, 1808, 1912, 1812, 1912,
     1818, 1820, 1836, 1826, 1912, 1843, 1912, 1903,   74, 1905,
     1907, 1909
    } ;

static const flex_int16_t yy_def[453] =
    {   0,
      447,    1,  448,  448,  448,  448,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  449,  449,
      449,  449,  449,   42,   42,  449,  449,  449,  449,   42,
      449,  449,  449,  449,  449,  449,  449,  449,  447,  447,
      447,  447,  447,  447,  447,  450,  447,  451,  447,  452,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  450,  447,  451,  447,
      452,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  449,  449,  449,  449,  449,  447,  447,  447,  447,
      447,  449,  449,  447,  447,  449,    0,  447,  447,  447,
      447,  447
    } ;

static const flex_int16_t yy_nxt[1973] =
    {   0,
        8,    9,   10,   11,   12,   13,    8,   14,   15,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,    8,   27,    8,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,    8,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   46,   46,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   46,   59,
       61,   61,   63,   63,   76,   62,   62,   64,   64,   69,
       71,   73,   72,   70,   74,  118,   77,   91,   80,   90,
      165,  166,  173,   81,   92,   83,   76,   84,  162,   78,
      172,   86,  163,   97,   73,  170,   87,   74,   77,   91,

       80,   88,   90,  168,   75,   76,   81,   92,   83,  107,
       84,   90,   78,   86,   94,   82,   97,   93,   98,   87,
       85,   79,   95,   99,   88,   97,  104,  101,   89,  108,
      114,  107,  447,  113,  162,  447,   94,  102,  163,  109,
       98,  105,  165,  166,   95,  110,   99,  164,  104,  101,
      107,  108,  114,  111,  161,  100,  113,  115,  116,   96,
      102,  109,  173,  175,  105,  447,  113,  103,  110,  172,
      108,  106,  170,  168,   76,  114,  111,  112,   73,  115,
      116,   74,  447,   65,   80,  447,  175,   77,  447,   81,
       71,  447,   72,  175,  177,  117,  121,  179,  164,  447,

       78,  119,  447,   83,  120,   84,  124,  161,  447,  122,
       68,   75,  125,  447,   86,   76,  177,   67,   90,   87,
      179,   82,  174,  123,   88,   66,  126,   91,  127,  182,
      179,   94,   79,  177,   92,  118,  128,  447,   85,   95,
       98,  131,  129,  447,  174,   99,  447,  130,  104,  132,
       90,   89,  182,  134,  182,  447,   97,  133,  447,  101,
      447,  135,  137,  105,  174,   65,  447,   93,  138,  102,
      141,  447,  107,  447,  108,  113,   96,  100,  447,  136,
      447,  139,  447,  447,  447,  447,  142,  187,   97,  447,
      114,  447,  140,  106,  143,  109,  144,  181,  148,  103,

      447,  110,  447,  447,  174,  447,  115,  116,  113,  111,
      187,  447,  149,  107,  447,  108,  175,  145,  178,  184,
      181,  206,  187,  181,  146,  447,  174,  447,  150,  151,
      447,  189,  147,  112,  185,  114,  200,  447,  447,  175,
      447,  178,  184,  206,  117,  152,  176,  178,  184,  153,
      154,  447,  155,  156,  189,   83,  185,  157,  158,  200,
      159,  179,  206,   88,  189,  178,  111,  152,  200,  181,
      182,  153,  154,  188,  155,  156,  185,  187,   83,  189,
      157,  158,  188,  159,  179,  185,   88,  191,  178,  111,
      160,  192,  181,  182,  180,  183,  188,  193,  184,  196,

      187,  194,  189,  188,  195,  188,  199,  185,  197,  196,
      191,  447,  190,  192,  447,  191,  197,  447,  199,  193,
      205,  184,  196,  194,  447,  202,  195,  186,  199,  200,
      447,  197,  196,  207,  196,  192,  197,  203,  447,  197,
      199,  193,  214,  205,  198,  194,  195,  202,  205,  199,
      209,  212,  200,  206,  213,  274,  207,  265,  213,  210,
      203,  201,  447,  207,  207,  214,  447,  214,  204,  447,
      214,  447,  209,  447,  212,  206,  213,  274,  447,  265,
      213,  212,  210,  177,  174,  447,  207,  211,  175,  447,
      214,  213,  447,  447,  208,  215,  447,  447,  274,  447,

      447,  178,  265,  447,  179,  218,  216,  447,  447,  447,
      447,  217,  447,  188,  447,  447,  181,  447,  175,  447,
      447,  447,  177,  265,  219,  182,  174,  220,  447,  185,
      178,  447,  184,  447,  447,  447,  226,  179,  447,  221,
      447,  447,  181,  188,  187,  265,  447,  447,  222,  447,
      182,  224,  447,  189,  447,  223,  447,  447,  192,  191,
      447,  184,  447,  447,  447,  447,  195,  225,  265,  447,
      193,  185,  447,  447,  447,  447,  227,  447,  447,  187,
      229,  447,  228,  280,  447,  447,  189,  191,  231,  196,
      447,  447,  230,  447,  447,  447,  447,  447,  447,  447,

      199,  447,  192,  197,  447,  447,  280,  447,  195,  447,
      447,  447,  232,  447,  193,  447,  200,  291,  447,  280,
      202,  447,  234,  447,  196,  447,  233,  206,  447,  447,
      447,  197,  203,  447,  447,  447,  207,  447,  447,  235,
      291,  447,  236,  199,  447,  291,  205,  447,  200,  239,
      212,  447,  447,  209,  278,  237,  447,  447,  447,  240,
      447,  447,  210,  204,  200,  447,  175,  207,  206,  238,
      447,  447,  213,  243,  205,  241,  447,  278,  447,  447,
      212,  447,  273,  214,  278,  242,  193,  200,  202,  175,
      211,  447,  177,  206,  244,  249,  255,  213,  192,  199,

      203,  447,  214,  205,  181,  273,  245,  273,  193,  213,
      202,  214,  212,  178,  177,  206,  447,  266,  249,  213,
      192,  199,  267,  203,  251,  214,  205,  181,  271,  209,
      250,  247,  270,  268,  248,  212,  178,  267,  210,  266,
      447,  270,  246,  447,  267,  276,  251,  447,  285,  268,
      271,  209,  447,  271,  266,  270,  268,  447,  447,  267,
      272,  210,  268,  267,  270,  270,  252,  195,  276,  271,
      288,  285,  268,  277,  270,  271,  179,  276,  269,  188,
      285,  253,  272,  294,  182,  447,  277,  447,  447,  195,
      447,  447,  447,  288,  271,  277,  447,  278,  447,  179,

      447,  272,  188,  288,  253,  447,  294,  182,  277,  254,
      194,  256,  257,  206,  277,  177,  447,  258,  294,  249,
      278,  259,  200,  260,  261,  262,  263,  279,  181,  182,
      447,  286,  194,  256,  257,  206,  289,  177,  274,  258,
      272,  447,  249,  447,  259,  200,  260,  261,  262,  263,
      447,  181,  182,  286,  264,  447,  273,  447,  289,  347,
      274,  281,  272,  281,  286,  282,  289,  282,  447,  272,
      280,  447,  286,  285,  288,  447,  292,  289,  295,  273,
      342,  275,  347,  281,  447,  281,  286,  282,  289,  282,
      292,  272,  295,  280,  347,  294,  285,  288,  292,  291,

      295,  447,  447,  342,  283,  287,  284,  290,  342,  265,
      272,  398,  292,  292,  295,  447,  295,  267,  294,  266,
      447,  447,  291,  447,  447,  447,  447,  293,  447,  330,
      296,  297,  447,  398,  447,  447,  268,  447,  271,  299,
      270,  298,  447,  447,  272,  447,  447,  447,  276,  447,
      447,  330,  447,  398,  265,  447,  266,  447,  267,  300,
      302,  447,  447,  301,  447,  268,  303,  447,  274,  273,
      330,  306,  447,  270,  447,  447,  277,  278,  447,  271,
      276,  447,  447,  447,  447,  272,  447,  447,  447,  447,
      305,  447,  304,  447,  273,  340,  447,  447,  307,  280,

      308,  447,  447,  447,  447,  447,  447,  278,  292,  447,
      281,  274,  447,  447,  282,  447,  447,  277,  340,  340,
      447,  447,  309,  447,  447,  285,  447,  447,  320,  286,
      317,  447,  310,  280,  447,  280,  311,  447,  288,  447,
      447,  447,  447,  447,  289,  292,  447,  447,  312,  447,
      320,  313,  447,  283,  274,  447,  280,  285,  294,  447,
      447,  314,  447,  447,  291,  447,  315,  295,  268,  321,
      286,  288,  447,  447,  286,  447,  274,  272,  266,  447,
      295,  318,  332,  285,  294,  289,  288,  316,  278,  319,
      276,  268,  291,  294,  292,  344,  286,  329,  447,  272,

      266,  447,  295,  291,  332,  295,  285,  294,  447,  288,
      280,  278,  341,  276,  285,  322,  292,  344,  324,  323,
      270,  276,  276,  332,  268,  447,  291,  294,  273,  447,
      265,  293,  281,  280,  291,  341,  282,  285,  344,  265,
      344,  447,  342,  270,  276,  341,  327,  268,  343,  345,
      294,  273,  265,  325,  281,  345,  359,  291,  282,  273,
      344,  265,  328,  295,  292,  342,  350,  447,  348,  276,
      342,  343,  345,  393,  447,  326,  343,  345,  345,  359,
      447,  447,  273,  346,  331,  295,  292,  447,  350,  447,
      348,  359,  276,  352,  447,  447,  393,  356,  447,  447,

      447,  333,  265,  351,  334,  393,  335,  350,  282,  295,
      336,  280,  294,  348,  337,  338,  352,  278,  268,  291,
      356,  447,  273,  352,  265,  351,  334,  356,  335,  348,
      282,  295,  336,  357,  280,  294,  359,  337,  338,  347,
      278,  268,  291,  351,  351,  273,  354,  339,  357,  447,
      360,  348,  447,  360,  352,  357,  429,  352,  340,  359,
      447,  447,  347,  356,  447,  351,  341,  447,  354,  447,
      357,  359,  360,  447,  349,  360,  447,  352,  357,  429,
      352,  361,  340,  429,  353,  447,  356,  355,  447,  362,
      342,  360,  447,  358,  360,  447,  447,  343,  447,  341,

      344,  447,  447,  347,  356,  447,  447,  345,  447,  447,
      447,  447,  447,  363,  347,  447,  447,  348,  342,  447,
      364,  447,  365,  447,  447,  343,  347,  356,  447,  447,
      366,  447,  447,  447,  356,  345,  350,  367,  347,  368,
      447,  447,  351,  352,  447,  344,  447,  447,  447,  347,
      447,  356,  447,  447,  447,  447,  357,  447,  369,  447,
      447,  447,  348,  447,  370,  359,  371,  447,  447,  447,
      447,  447,  447,  352,  372,  360,  360,  350,  373,  447,
      447,  356,  360,  351,  447,  447,  350,  447,  374,  348,
      447,  357,  347,  447,  447,  447,  382,  360,  375,  447,

      359,  357,  447,  341,  360,  447,  356,  447,  350,  447,
      350,  348,  447,  357,  447,  347,  360,  360,  344,  382,
      351,  356,  359,  360,  382,  357,  341,  376,  344,  356,
      351,  352,  350,  447,  348,  378,  377,  340,  447,  359,
      344,  341,  351,  345,  356,  359,  357,  357,  447,  340,
      344,  381,  351,  343,  352,  394,  347,  359,  378,  397,
      340,  380,  359,  379,  341,  397,  345,  429,  357,  447,
      357,  384,  340,  383,  386,  395,  343,  399,  394,  347,
      447,  343,  397,  400,  402,  394,  395,  405,  397,  397,
      429,  385,  387,  394,  429,  397,  388,  395,  447,  399,

      447,  447,  389,  447,  341,  400,  402,  390,  395,  391,
      405,  404,  395,  340,  387,  405,  394,  400,  388,  399,
      399,  400,  447,  396,  402,  389,  402,  341,  400,  447,
      390,  447,  391,  404,  404,  447,  340,  392,  447,  400,
      447,  447,  399,  400,  447,  447,  402,  447,  405,  447,
      393,  447,  447,  404,  394,  447,  404,  395,  447,  447,
      447,  447,  401,  397,  447,  447,  403,  447,  447,  398,
      447,  405,  447,  407,  447,  400,  406,  408,  447,  409,
      399,  447,  393,  398,  394,  394,  410,  447,  447,  447,
      447,  411,  447,  397,  395,  404,  447,  413,  393,  447,

      447,  405,  412,  447,  447,  398,  447,  447,  394,  404,
      393,  398,  394,  447,  447,  394,  400,  414,  417,  399,
      400,  393,  399,  405,  415,  398,  395,  399,  402,  405,
      393,  404,  395,  393,  405,  394,  447,  404,  400,  447,
      417,  399,  416,  419,  426,  405,  405,  447,  395,  399,
      402,  406,  400,  395,  395,  404,  428,  405,  393,  447,
      417,  401,  405,  395,  447,  425,  419,  426,  405,  418,
      402,  447,  425,  420,  400,  395,  426,  404,  447,  428,
      428,  393,  426,  447,  447,  430,  447,  425,  447,  447,
      422,  447,  447,  447,  425,  430,  447,  421,  400,  447,

      425,  423,  429,  430,  447,  426,  395,  425,  430,  447,
      429,  393,  447,  419,  427,  405,  447,  447,  430,  430,
      400,  447,  432,  423,  447,  429,  430,  430,  395,  431,
      428,  447,  447,  429,  393,  447,  419,  431,  405,  447,
      425,  447,  425,  424,  447,  426,  447,  447,  447,  447,
      430,  447,  429,  434,  428,  430,  447,  447,  425,  447,
      447,  430,  425,  426,  426,  447,  425,  447,  433,  429,
      429,  440,  447,  447,  447,  435,  428,  426,  436,  429,
      425,  447,  425,  440,  428,  447,  426,  426,  425,  430,
      447,  441,  429,  429,  440,  426,  437,  429,  447,  428,

      438,  447,  441,  447,  440,  447,  440,  428,  438,  425,
      447,  447,  440,  447,  441,  447,  440,  430,  447,  426,
      447,  441,  447,  447,  429,  441,  447,  428,  447,  441,
      447,  425,  441,  447,  440,  442,  445,  441,  440,  447,
      430,  441,  426,  447,  445,  440,  447,  429,  447,  447,
      428,  439,  443,  447,  445,  447,  447,  440,  445,  441,
      441,  440,  447,  447,  441,  447,  445,  444,  447,  447,
      447,  444,  447,  447,  447,  447,  446,  445,  447,  447,
      447,  447,  447,  447,  447,  445,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  445,  447,  447,  447,  447,

      447,  447,  447,   60,   60,  167,  167,  169,  169,  171,
      171,    7,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447
    } ;

static const flex_int16_t yy_chk[1973] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    6,   21,    3,    4,    5,    6,   17,
       18,   20,   18,   17,   20,  449,   22,   27,   23,   26,
       64,   64,  173,   23,   27,   24,   21,   24,   62,   22,
      171,   25,   62,   29,   20,  169,   25,   20,   22,   27,

       23,   25,   26,  167,   20,   21,   23,   27,   24,   33,
       24,   26,   22,   25,   28,   23,   29,   27,   30,   25,
       24,   22,   28,   30,   25,   29,   32,   31,   25,   34,
       37,   33,   46,   36,  162,   46,   28,   31,  162,   35,
       30,   32,  166,  166,   28,   35,   30,  164,   32,   31,
       33,   34,   37,   35,  161,   30,   36,   38,   38,   28,
       31,   35,   71,   74,   32,   46,   36,   31,   35,   70,
       34,   32,   68,   66,   40,   37,   35,   35,   39,   38,
       38,   39,   40,   65,   42,   40,   74,   41,   42,   42,
       72,   42,   72,   74,   76,   38,   40,   78,   63,   41,

       41,   39,   41,   43,   39,   43,   42,   61,   43,   41,
       14,   39,   42,   45,   44,   40,   76,   13,   45,   44,
       78,   42,   73,   41,   44,   12,   43,   47,   43,   81,
       78,   48,   41,   76,   47,   45,   44,   47,   43,   48,
       50,   45,   44,   48,   73,   50,   48,   44,   52,   47,
       45,   44,   81,   48,   81,   49,   49,   47,   49,   51,
       52,   48,   50,   52,   73,    9,   51,   47,   50,   51,
       52,    7,   53,    0,   54,   56,   48,   50,   56,   49,
       53,   51,   54,   53,    0,   54,   52,   86,   49,    0,
       57,    0,   51,   52,   53,   55,   54,   80,   56,   51,

       55,   55,   57,   55,   75,   57,   58,   58,   56,   55,
       86,   58,   57,   53,   58,   54,   75,   55,   77,   83,
       80,  109,   86,   80,   55,    0,   75,    0,   58,   58,
        0,   88,   55,   55,   84,   57,  105,    0,    0,   75,
        0,   77,   83,  109,   58,   59,   75,   77,   83,   59,
       59,    0,   59,   59,   88,   59,   84,   59,   59,  105,
       59,   79,  109,   59,   88,   79,   59,   59,  105,   82,
       82,   59,   59,   87,   59,   59,   84,   89,   59,   89,
       59,   59,   89,   59,   79,   85,   59,   90,   79,   59,
       59,   94,   82,   82,   79,   82,   87,   95,   85,   98,

       89,   96,   89,   87,   97,   89,  104,   85,   99,  100,
       90,    0,   89,   94,    0,   90,  100,    0,  106,   95,
      108,   85,   98,   96,    0,  107,   97,   85,  104,  106,
        0,   99,  100,  111,   98,   94,   99,  107,    0,  100,
      106,   95,  116,  108,  100,   96,   97,  107,  108,  104,
      113,  114,  106,  112,  115,  189,  111,  175,  117,  113,
      107,  106,    0,  112,  111,  116,  118,  117,  107,  118,
      116,    0,  113,    0,  114,  112,  115,  189,    0,  175,
      117,  114,  113,  121,  119,  120,  112,  113,  120,  121,
      117,  115,  121,  119,  112,  117,  119,  122,  189,  118,

      122,  122,  175,    0,  123,  121,  119,  123,    0,  124,
      129,  120,  124,  129,    0,    0,  124,  125,  120,    0,
      125,    0,  121,  176,  122,  125,  119,  123,  126,  127,
      122,  126,  126,    0,    0,    0,  129,  123,  127,  124,
        0,  127,  124,  129,  128,  176,  128,    0,  125,  128,
      125,  127,    0,  130,  131,  126,  130,  131,  134,  131,
      132,  126,  133,  132,    0,  133,  136,  128,  176,  134,
      135,  127,  134,    0,  139,  136,  130,  139,  136,  128,
      134,  135,  131,  199,  135,    0,  130,  131,  136,  137,
        0,  137,  135,  132,  137,  133,  140,    0,  138,  140,

      141,  138,  134,  138,    0,    0,  199,  139,  136,    0,
      141,    0,  137,  141,  135,  142,  142,  209,  142,  199,
      143,    0,  141,    0,  137,  146,  138,  145,  146,  140,
      143,  138,  143,  143,  147,  145,  147,  147,  145,  142,
      209,  144,  143,  141,  144,  209,  144,  149,  142,  145,
      149,    0,    0,  148,  193,  143,    0,  148,  146,  147,
      148,    0,  148,  143,  159,    0,  159,  147,  145,  144,
        0,    0,  150,  149,  144,  148,  150,  193,  151,  150,
      149,  151,  188,  151,  193,  148,  156,  159,  153,  159,
      148,    0,  153,  155,  150,  156,  159,  155,  152,  152,

      153,    0,  156,  153,  156,  188,  151,  188,  156,  150,
      153,  151,  152,  152,  153,  155,    0,  177,  156,  155,
      152,  152,  178,  153,  157,  156,  153,  156,  184,  157,
      156,  153,  182,  179,  155,  152,  152,  180,  157,  177,
        0,  183,  152,    0,  178,  191,  157,    0,  202,  180,
      184,  157,    0,  186,  177,  182,  179,    0,    0,  180,
      187,  157,  179,  178,  183,  182,  157,  158,  191,  184,
      206,  202,  180,  192,  183,  186,  158,  191,  180,  158,
      202,  158,  187,  213,  158,    0,  194,    0,    0,  158,
        0,    0,    0,  206,  186,  192,    0,  194,    0,  158,

        0,  187,  158,  206,  158,    0,  213,  158,  194,  158,
      160,  160,  160,  160,  192,  160,    0,  160,  213,  160,
      194,  160,  160,  160,  160,  160,  160,  194,  160,  160,
        0,  203,  160,  160,  160,  160,  207,  160,  190,  160,
      190,    0,  160,    0,  160,  160,  160,  160,  160,  160,
        0,  160,  160,  203,  160,    0,  190,    0,  207,  277,
      190,  200,  190,  201,  204,  200,  208,  201,  216,  249,
      201,  216,  203,  204,  208,    0,  210,  207,  214,  190,
      268,  190,  277,  200,    0,  201,  204,  200,  208,  201,
      211,  249,  215,  201,  277,  215,  204,  208,  210,  211,

      214,  216,    0,  268,  200,  204,  201,  208,  268,  217,
      249,  350,  211,  210,  215,    0,  214,  219,  215,  218,
        0,  217,  211,  218,  217,  219,  218,  211,  219,  260,
      215,  217,  220,  350,  221,  220,  220,  221,  223,  219,
      222,  218,  224,  222,  225,  224,  223,  228,  228,  223,
      228,  260,  225,  350,  217,  225,  218,    0,  219,  220,
      223,  226,    0,  222,  226,  220,  225,  221,  227,  226,
      260,  228,    0,  222,  230,  224,  229,  230,  227,  223,
      228,  227,    0,  231,  229,  225,  231,  229,  232,    0,
      227,  232,  226,  233,  226,  265,  233,    0,  229,  234,

      230,  238,  234,    0,  238,  234,  243,  230,  242,  243,
      235,  227,  242,    0,  235,  242,  231,  229,  265,  265,
      235,  232,  234,  235,  236,  236,  233,  236,  246,  237,
      242,    0,  235,  246,  238,  234,  235,  237,  239,  243,
      237,  239,    0,    0,  240,  242,  299,    0,  236,  299,
      246,  237,  240,  235,  259,  240,  246,  236,  244,  241,
      244,  239,  241,  244,  241,    0,  240,  245,  259,  246,
      237,  239,  245,    0,  247,  245,  259,  250,  247,  299,
      250,  244,  262,  247,  248,  240,  248,  241,  250,  245,
      253,  259,  241,  244,  252,  273,  247,  259,    0,  250,

      247,    0,  250,  252,  262,  245,  247,  248,    0,  248,
      256,  250,  266,  253,  256,  247,  252,  273,  250,  248,
      254,  254,  253,  262,  254,    0,  252,  258,  254,    0,
      255,  252,  255,  256,  258,  266,  255,  256,  275,  261,
      273,    0,  269,  254,  254,  266,  256,  254,  270,  274,
      258,  254,  255,  254,  255,  275,  292,  258,  255,  261,
      275,  261,  258,  263,  263,  269,  280,    0,  278,  263,
      269,  270,  274,  343,    0,  255,  270,  274,  275,  292,
        0,    0,  261,  275,  261,  263,  263,    0,  280,    0,
      278,  292,  263,  282,    0,    0,  343,  285,    0,    0,

        0,  263,  264,  281,  264,  343,  264,  280,  264,  264,
      264,  264,  264,  278,  264,  264,  282,  264,  264,  264,
      285,    0,  264,  282,  264,  281,  264,  285,  264,  279,
      264,  264,  264,  286,  264,  264,  293,  264,  264,  279,
      264,  264,  264,  283,  281,  264,  284,  264,  287,  297,
      294,  279,  297,  296,  283,  286,  399,  284,  297,  293,
        0,    0,  279,  287,    0,  283,  298,    0,  284,  298,
      287,  293,  294,  302,  279,  296,  302,  283,  286,  399,
      284,  297,  297,  399,  283,  300,  287,  284,  300,  298,
      300,  294,  301,  287,  296,  301,    0,  301,  303,  298,

      304,  303,  305,  320,  338,  305,  302,  305,  306,    0,
        0,  306,  304,  300,  307,  304,  307,  308,  300,  307,
      301,  314,  304,    0,  314,  301,  320,  338,    0,  308,
      305,  303,  308,    0,  338,  305,  309,  307,  320,  308,
      311,  306,  310,  311,  309,  304,    0,  309,  312,  307,
      310,  312,  315,  310,  314,  315,  313,  316,  309,    0,
      316,    0,  308,    0,  310,  317,  311,  317,  313,  319,
      317,  313,  319,  311,  312,  323,  318,  309,  313,    0,
        0,  312,  328,  310,  318,  315,  321,  318,  317,  324,
      316,  322,  321,    0,    0,    0,  329,  323,  318,    0,

      317,  313,  319,  322,  328,    0,  322,    0,  321,    0,
      327,  324,    0,  322,    0,  321,  323,  318,  325,  329,
      326,  327,  333,  328,  329,  330,  322,  321,  331,  322,
      334,  326,  327,    0,  324,  325,  322,  326,    0,  336,
      325,  336,  326,  334,  327,  333,  335,  330,    0,  331,
      331,  327,  334,  337,  326,  344,  335,  333,  325,  348,
      326,  326,  336,  325,  336,  349,  334,  402,  335,    0,
      330,  334,  331,  331,  336,  345,  337,  351,  344,  335,
        0,  337,  348,  352,  354,  344,  346,  357,  349,  348,
      402,  335,  339,  346,  402,  349,  339,  345,  361,  351,

        0,  361,  339,    0,  339,  352,  354,  339,  346,  339,
      357,  356,  345,  339,  339,  357,  346,  353,  339,  351,
      353,  355,    0,  346,  355,  339,  354,  339,  352,    0,
      339,  361,  339,  356,  358,  362,  339,  339,  362,  353,
        0,  363,  353,  355,  363,    0,  355,    0,  358,  364,
      364,  365,  364,  356,  365,  367,  358,  366,  367,    0,
      368,  366,  353,  368,  366,    0,  355,  374,  362,  369,
      374,  358,    0,  364,  363,  371,  358,  365,  369,  366,
      370,  369,  364,  376,  365,  383,  368,  371,  367,  370,
      371,  369,  370,  368,  366,  372,  373,  371,  378,  373,

      374,  373,  370,  375,  372,  376,  375,  372,  383,  377,
      379,  369,  379,    0,    0,  383,  380,  372,  381,  380,
      371,  378,  370,  377,  373,  376,  382,  384,  388,  373,
      378,  377,  384,  379,  385,  379,  375,  372,  380,    0,
      381,  380,  379,  387,  395,  387,  377,    0,  382,  384,
      388,  377,  390,  391,  384,  390,  397,  385,  391,    0,
      381,  380,  385,  382,    0,  394,  387,  395,  387,  384,
      388,    0,  396,  387,  390,  391,  395,  390,    0,  397,
      397,  391,  396,  407,    0,  400,  407,  394,    0,    0,
      391,    0,    0,    0,  396,  401,    0,  390,  392,    0,

      408,  392,  401,  403,    0,  396,  392,  394,  400,  408,
      403,  392,  408,  392,  396,  392,  407,    0,  401,  400,
      392,  410,  408,  392,  410,  401,  403,  421,  392,  401,
      410,    0,  411,  403,  392,  411,  392,  403,  392,    0,
      416,    0,  408,  392,  409,  409,  412,  409,  414,  412,
      421,  414,  412,  410,  410,  413,  413,  415,  419,  413,
      415,  421,  416,  422,  418,  411,  420,    0,  409,  418,
      423,  426,    0,    0,    0,  412,  419,  409,  413,  412,
      419,  414,  416,  427,  420,    0,  422,  418,  420,  413,
      415,  429,  418,  423,  426,  422,  418,  423,    0,  419,

      419,    0,  431,    0,  426,    0,  427,  420,  420,  424,
      432,    0,  433,  432,  429,  433,  427,  424,    0,  424,
      434,  429,    0,  434,  424,  431,  435,  424,    0,  435,
      436,  424,  431,  436,  437,  433,  441,  437,  439,    0,
      424,  439,  424,  432,  444,  433,  442,  424,    0,  442,
      424,  424,  435,  434,  443,    0,    0,  437,  441,  435,
      437,  439,  443,  436,  439,  443,  444,  437,    0,  446,
        0,  439,  446,    0,    0,    0,  443,  441,    0,  442,
        0,    0,    0,    0,    0,  444,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  443,    0,    0,    0,    0,

        0,    0,  446,  448,  448,  450,  450,  451,  451,  452,
      452,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "PascalDSL.l"
#line 2 "PascalDSL.l"
# include "common.h"
# include "PascalDSL.tab.h"

char buffer[200];
typedef void (*addParserErrorText)(char* message);
static addParserErrorText m_addParserErrorText;

int count(void);
void* addTextPtr;

int count(void) { return yylineno; }
int yy_pascal_lex_get_line(void) { return count(); }
int yy_pascal_lex_getlines(void) { return count(); }
#line 1296 "lex.pascal.c"

#line 1298 "lex.pascal.c"

#define INITIAL 0
#define Comment1 1
#define Comment2 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "PascalDSL.l"


#line 1520 "lex.pascal.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 448 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1912 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "PascalDSL.l"
{ count(); /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "PascalDSL.l"
{ count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "PascalDSL.l"
{ count(); /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 54 "PascalDSL.l"
{ count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "PascalDSL.l"
{ count(); /* DO NOTHING */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 57 "PascalDSL.l"
{ count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "PascalDSL.l"
{ count(); BEGIN(Comment1); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 60 "PascalDSL.l"
{ count(); ++yylineno;      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "PascalDSL.l"
{ count(); BEGIN(INITIAL);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "PascalDSL.l"
{ count(); BEGIN(Comment2); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 64 "PascalDSL.l"
{ count(); ++yylineno;      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "PascalDSL.l"
{ count(); BEGIN(INITIAL);  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "PascalDSL.l"
{ /* empty */ }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 68 "PascalDSL.l"
{ count(); ++yylineno; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 70 "PascalDSL.l"
{ count(); return TOK_PAS_AND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "PascalDSL.l"
{ count(); return TOK_PAS_ARRAY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 72 "PascalDSL.l"
{ count(); return TOK_PAS_BEGIN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 73 "PascalDSL.l"
{ count(); return TOK_PAS_CASE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 74 "PascalDSL.l"
{ count(); return TOK_PAS_CONST; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 75 "PascalDSL.l"
{ count(); return TOK_PAS_DIV; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "PascalDSL.l"
{ count(); return TOK_PAS_DO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 77 "PascalDSL.l"
{ count(); return TOK_PAS_DOWNTO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 78 "PascalDSL.l"
{ count(); return TOK_PAS_ELSE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 79 "PascalDSL.l"
{ count(); return TOK_PAS_END; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 80 "PascalDSL.l"
{ count(); return TOK_PAS_FILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "PascalDSL.l"
{ count(); return TOK_PAS_FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 82 "PascalDSL.l"
{ count(); return TOK_PAS_FORWARD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "PascalDSL.l"
{ count(); return TOK_PAS_FUNCTION; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "PascalDSL.l"
{ count(); return TOK_PAS_GOTO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "PascalDSL.l"
{ count(); return TOK_PAS_IF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "PascalDSL.l"
{ count(); return TOK_PAS_IN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "PascalDSL.l"
{ count(); return TOK_PAS_LABEL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "PascalDSL.l"
{ count(); return TOK_PAS_LIBRARY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "PascalDSL.l"
{ count(); return TOK_PAS_MOD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "PascalDSL.l"
{ count(); return TOK_PAS_NIL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "PascalDSL.l"
{ count(); return TOK_PAS_NOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "PascalDSL.l"
{ count(); return TOK_PAS_OF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "PascalDSL.l"
{ count(); return TOK_PAS_OR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 94 "PascalDSL.l"
{ count(); return TOK_PAS_PACKED; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 95 "PascalDSL.l"
{ count(); return TOK_PAS_PROCEDURE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "PascalDSL.l"
{ count(); return TOK_PAS_PROGRAM; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "PascalDSL.l"
{ count(); return TOK_PAS_RECORD; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "PascalDSL.l"
{ count(); return TOK_PAS_REPEAT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 99 "PascalDSL.l"
{ count(); return TOK_PAS_SET; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 "PascalDSL.l"
{ count(); return TOK_PAS_THEN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 101 "PascalDSL.l"
{ count(); return TOK_PAS_TO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 102 "PascalDSL.l"
{ count(); return TOK_PAS_TYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 103 "PascalDSL.l"
{ count(); return TOK_PAS_UNIT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 104 "PascalDSL.l"
{ count(); return TOK_PAS_UNTIL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 105 "PascalDSL.l"
{ count(); return TOK_PAS_VAR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 106 "PascalDSL.l"
{ count(); return TOK_PAS_WHILE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 107 "PascalDSL.l"
{ count(); return TOK_PAS_WITH; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "PascalDSL.l"
{ return TOK_PAS_ID;  }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "PascalDSL.l"
{
  sprintf(buffer, "An integer: %s (%d)\n", yytext,
  atoi( yytext ) );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "PascalDSL.l"
{
  sprintf(buffer, "A float: %s (%g)\n", yytext,
  atof( yytext ) );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "PascalDSL.l"
{ return ';'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "PascalDSL.l"
{ return '.'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "PascalDSL.l"
{
  return
  sprintf( buffer, "An operator: %s\n", yytext );
  MessageBox(0,buffer,"test",0);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "PascalDSL.l"
{
  sprintf( buffer, "Unrecognized character: %s\n", yytext );
  pascalerror(buffer);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "PascalDSL.l"
ECHO;
	YY_BREAK
#line 1898 "lex.pascal.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
case YY_STATE_EOF(Comment2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 448 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 448 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 447);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 138 "PascalDSL.l"


void yy_pascal_lex_parser_error(void (*func)(char*)) {
  m_addParserErrorText = func;
}

int pascalwrap(void) { return 1; }

void pascalerror(char* m)
{
  char bu[320];
  sprintf(bu,"error: %d: %s",
  yylineno, m);
  m_addParserErrorText(bu);
}

BOOL yy_pascal_lex_main(char* filename)
{
  BOOL result;
  yyin = fopen(filename,"r");
  if (!yyin) {
    sprintf(buffer, "could not open file: %s", filename);
    m_addParserErrorText(buffer);
    return false;
  }

  //yylex();
  result = pascalparse();
  fclose(yyin);

  return result;
}

void yy_pascal_lex_close(void) {
  fclose(yyin);
}

void __declspec(dllexport) yy_pascal_lex_parser_error(void (*func)(char*));
void __declspec(dllexport) yy_pascal_lex_close(void);

int  __declspec(dllexport) yy_pascal_lex_get_line(void);
int  __declspec(dllexport) yy_pascal_lex_getlines(void);

BOOL __declspec(dllexport) yy_pascal_lex_main(char* filename);


