
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[393] =
    {   0,
       12,   12,   10,   10,   76,   74,   12,   13,   13,   74,
       74,   63,   62,   74,   65,   66,   60,   59,   71,   58,
       72,   61,   38,   56,   57,   74,   64,   74,   73,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   67,   68,   69,   13,   70,   75,   10,
       75,   12,   50,    0,   41,    0,    3,    7,    0,    0,
        0,    0,    0,    0,    9,    1,    0,   38,   40,   64,
       53,   52,   49,   51,   54,   55,   40,   40,   40,    0,
       40,    0,   40,   40,    0,   40,   40,   40,    0,   26,
       26,   40,    0,   40,    0,   29,   29,   40,   40,    0,

       40,    0,   40,    0,   35,   40,   35,   40,    0,    0,
        0,    0,   43,    0,    0,   26,    0,    0,   35,    0,
        0,   26,   10,    0,   11,   42,    0,   41,    0,    3,
        4,    7,    7,    8,    7,    0,   47,    0,    0,   48,
       47,    0,    1,    2,   39,   40,   40,    0,   40,    0,
        0,    0,    0,   40,    0,   40,    0,   40,    0,    0,
       40,    0,   24,   24,   40,    0,   24,   40,    0,   28,
       28,   40,    0,   40,   40,    0,    0,    0,    0,   40,
        0,   34,   34,   40,    0,   40,    0,    0,    0,    0,
        0,   43,    0,   34,   28,    0,   24,    0,    0,   24,

        0,   34,   24,   42,    7,    0,    0,   46,    0,   40,
        0,   40,    0,    0,   40,    0,    0,   40,    0,   18,
       18,   40,   40,   40,   40,    0,    0,    0,    0,    0,
       18,   40,    0,   40,    0,    0,   40,    0,   40,    0,
       40,    0,   40,    0,    0,    0,   40,    0,   36,   36,
       37,   37,    0,    0,   18,   36,    0,   18,   37,    0,
        0,   18,    0,    0,   18,    7,   44,   45,   44,   14,
       14,   15,   15,   14,   40,    0,   14,   40,    0,   40,
        0,   40,    0,   21,   21,   40,    0,   21,   23,   23,
       40,    0,   23,   27,   27,   40,    0,   40,    0,   40,

        0,    0,    0,   40,    0,   23,    0,    0,   15,    0,
       21,   14,   23,   27,    0,   15,   14,    7,    7,   16,
       16,   17,   17,   40,    0,   20,   20,   40,    0,   20,
       40,    0,   40,    0,   40,    0,   40,    0,    0,    0,
       33,   33,   17,   16,    0,   16,   17,    0,   16,    7,
       40,    0,   22,   22,   22,   40,    0,   40,    0,   31,
       31,   40,    0,   31,   31,    0,   22,   22,    7,   19,
       19,   25,   25,   40,    0,   40,    0,    0,   19,   19,
        7,   30,   30,   32,   32,   30,    7,    5,    5,    5,
        6,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
       27,   32,   33,   27,   27,   34,   35,   36,   37,   38,
       27,   39,   40,   41,   42,   43,   44,   27,   27,   27,
       45,   46,   47,    1,   27,    1,   26,   27,   28,   29,

       30,   31,   27,   32,   33,   27,   27,   34,   35,   36,
       37,   38,   27,   39,   40,   41,   42,   43,   44,   27,
       27,   27,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[404] =
    {   0,
        0,    0,   48,   49,  955,  956,  952,  956,  956,  930,
       47,  956,  956,  943,  956,  956,  938,  956,  956,  956,
       28,   42,   39,  927,  956,  926,   44,  925,  922,  927,
       52,   51,   53,   54,   57,   55,   60,   64,   59,   80,
       86,   78,   88,  108,  956,  956,  130,  956,  956,  942,
      106,  942,  956,  116,  128,  130,  940,  109,   89,  925,
       26,   95,  894,  134,  956,  906,  889,   65,  890,  956,
      956,  956,  956,  956,  956,  956,  887,  155,  101,  119,
      146,   97,  138,  161,  153,  165,  104,  156,  152,  886,
      956,  170,  166,  177,   98,  885,  956,  178,  187,  174,

      181,  167,  184,  188,  884,  190,  186,  193,  197,  234,
      237,  242,  956,  215,  219,  956,  225,  212,  228,  220,
      230,  264,  899,  258,  956,  956,  272,  313,  304,  898,
      956,  896,  309,  956,  284,  273,  956,  250,  881,  956,
      956,  307,  894,  956,  877,  302,  306,  300,  311,  286,
      288,  247,  305,  324,  226,  334,  314,  343,  337,  347,
      348,  289,  876,  956,  365,  333,  361,  353,  260,  875,
      956,  379,  359,  375,  371,  372,  298,  367,  383,  385,
      364,  873,  956,  393,  373,  398,  387,  843,  419,  425,
      434,  439,  412,  397,  408,  428,  407,  439,  434,  425,

      429,  411,  463,  491,  461,  872,  870,  956,  867,  460,
      459,  479,  424,  474,  483,  478,  482,  497,  182,  864,
      956,  492,  498,  505,  506,  511,  500,  501,  509,  443,
      528,  533,  521,  534,  515,  527,  547,  535,  552,  223,
      548,  546,  559,  543,  560,  568,  561,  563,  858,  956,
      851,  956,  558,  575,  566,  590,  581,  542,  574,  592,
      591,  956,  597,  589,  621,  632,  956,  956,  956,  788,
      956,  780,  956,  956,  618,  494,  550,  629,  614,  617,
      616,  630,  633,  728,  956,  649,  634,  645,  692,  956,
      654,  643,  644,  631,  956,  655,  650,  669,  648,  672,

      666,  667,  676,  683,  664,  677,  684,  689,  679,  701,
      682,  956,  694,  703,  700,  704,  728,  734,  738,  626,
      956,  585,  956,  725,  702,  511,  956,  727,  713,  739,
      736,  711,  737,  731,  751,  745,  763,  406,  754,  760,
      468,  956,  956,  755,  771,  956,  748,  761,  784,  792,
      779,  766,  465,  956,  782,  798,  787,  808,  799,  388,
      956,  811,  793,  796,  807,  804,  956,  819,  836,  350,
      956,  347,  956,  832,  813,  842,  824,  837,  833,  839,
      863,  315,  956,  266,  956,  956,  861,  872,  149,  877,
      956,  956,  912,  915,  917,  145,  920,  923,  926,  929,

      932,  935,  938
    } ;

static const flex_int16_t yy_def[404] =
    {   0,
      392,    1,  393,  393,  392,  392,  392,  392,  392,  392,
      394,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  395,  392,  392,  392,  392,  392,  392,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  397,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  394,  392,  398,  399,  400,  392,  392,
      392,  392,  392,  392,  392,  401,  392,  395,  395,  392,
      392,  392,  392,  392,  392,  392,  396,  396,  396,  392,
      396,  392,  396,  396,  392,  396,  396,  396,  392,  396,
      392,  396,  392,  396,  392,  396,  392,  396,  396,  392,

      396,  392,  396,  392,  396,  396,  392,  396,  392,  397,
      397,  402,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  394,  394,  398,  399,
      392,  400,  400,  392,  400,  392,  392,  392,  392,  392,
      392,  392,  401,  392,  392,  396,  396,  392,  396,  392,
      392,  392,  392,  396,  392,  396,  392,  396,  392,  392,
      396,  392,  396,  392,  396,  392,  392,  396,  392,  396,
      392,  396,  392,  396,  396,  392,  392,  392,  392,  396,
      392,  396,  392,  396,  392,  396,  392,  392,  397,  397,
      402,  397,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  394,  400,  392,  392,  392,  392,  396,
      392,  396,  392,  392,  396,  392,  392,  396,  392,  396,
      392,  396,  396,  396,  396,  392,  392,  392,  392,  392,
      392,  396,  392,  396,  392,  392,  396,  392,  396,  392,
      396,  392,  396,  392,  392,  392,  396,  392,  396,  392,
      396,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  400,  392,  392,  392,  396,
      392,  396,  392,  392,  396,  392,  392,  396,  392,  396,
      392,  396,  392,  396,  392,  396,  392,  392,  396,  392,
      396,  392,  392,  396,  392,  396,  392,  396,  392,  396,

      392,  392,  392,  396,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  400,  400,  396,
      392,  396,  392,  396,  392,  396,  392,  396,  392,  392,
      396,  392,  396,  392,  396,  392,  396,  392,  392,  392,
      396,  392,  392,  392,  392,  392,  392,  392,  392,  400,
      396,  392,  396,  392,  392,  396,  392,  396,  392,  396,
      392,  396,  392,  392,  392,  392,  392,  392,  400,  396,
      392,  396,  392,  396,  392,  396,  392,  392,  392,  392,
      400,  396,  392,  396,  392,  392,  400,  403,  403,  403,
      392,    0,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392
    } ;

static const flex_int16_t yy_nxt[1007] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   11,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   30,   35,   36,   30,   37,   38,   39,   40,   41,
       42,   30,   30,   43,   44,    6,   45,   46,   47,   48,
       50,   50,   55,   59,   65,   67,   55,   68,   60,   66,
       51,   51,  138,   61,   62,   72,   73,   74,   63,   69,
       69,   69,   69,   69,  138,   69,   64,   69,   69,   86,
       81,   67,   69,   68,   98,   78,   83,   90,   84,   94,
       87,   92,   56,   79,   96,   88,   69,   99,   69,   82,

       80,   85,   89,   93,   69,   91,   69,  100,   95,  101,
      133,  134,   97,  111,  105,  103,  106,  111,  124,   69,
      108,   55,   69,  125,  136,   55,  107,  155,  102,  126,
      126,  126,   54,  139,  104,  128,  109,  136,  135,  128,
      149,  171,  163,  139,  151,  155,  171,   77,  152,  150,
      141,  391,  164,  112,  113,  114,   69,  135,  150,  115,
      116,   56,  109,  117,   69,  118,  119,  153,  120,  136,
      138,  121,  139,   69,   69,  129,  154,  156,  122,   69,
      146,  159,  142,   69,  147,  162,  157,  166,   69,  158,
      164,  165,  157,  169,  155,   69,   69,  168,  161,   69,

      167,  160,   69,  148,  166,   69,  177,  181,   69,  159,
      178,   69,  173,  162,  169,  181,  172,  279,  169,  174,
      170,  180,  179,  175,  182,  171,  173,  185,  183,  181,
      279,  184,  183,  186,  185,  176,  183,  187,  185,  188,
      159,  187,  188,  188,  110,  187,  188,  190,  162,  155,
      151,  190,  177,  173,  152,  169,  178,  297,  219,  194,
      159,  185,  171,  193,  157,  166,  164,  195,  198,  150,
      124,  297,  213,  196,  219,  125,  197,   55,  199,  112,
      113,   55,  112,  113,   69,  238,  134,  191,  192,  151,
      207,  169,  159,  152,  155,  213,  177,  162,  207,  166,

      178,  206,  200,  201,  202,  185,   54,  171,  238,  128,
      133,  134,  203,  128,  204,  204,  204,   56,   55,  205,
       69,  206,   55,  208,   69,  213,  216,  211,  233,   69,
      213,  212,  205,   69,  216,  206,  211,  233,  135,  211,
      242,  210,   69,  221,  211,  216,  242,  207,  214,  129,
      211,  215,   69,  217,  213,  209,  218,  135,   56,  216,
      235,   69,  221,  220,  227,   69,   69,  228,   69,  229,
      222,   69,  219,  223,  227,  224,  221,  228,  237,  229,
      230,  235,  221,   69,  240,  226,  225,  232,  235,   69,
      230,  226,  234,   69,  244,  231,  233,   69,  243,  244,

      233,  238,  250,   69,  239,  248,   69,  240,  240,  236,
      244,   69,  248,  235,  242,  244,   69,  241,  252,  244,
      245,  250,  249,  242,  188,  242,  247,  240,  188,  251,
      188,  246,  238,  248,  188,  252,  110,  240,  248,  190,
      219,  250,  252,  190,  188,  248,  252,  363,  188,  248,
      240,  233,  248,  213,  363,  238,  254,  221,  221,  259,
      253,  235,  273,  134,  112,  113,  244,  211,  250,  216,
      112,  113,  273,  240,  216,  287,  255,  258,   69,  191,
      192,  242,  257,   69,  112,  113,   69,  256,  260,  266,
      261,  287,  262,  228,  252,  263,   55,   69,  271,  270,

       55,   69,  264,  216,  248,  242,  230,  271,  271,  266,
       69,  265,  273,  271,  276,   69,   69,  272,  276,  275,
      273,  271,  274,   69,   69,  280,  276,  273,  321,   69,
      277,  276,  278,  281,  282,  284,   56,  283,  286,  285,
      281,  285,  321,  287,  281,  279,  283,  283,  281,  283,
      290,   69,   69,  285,  287,  292,  290,  285,  285,  288,
      287,  281,  289,  292,  283,   69,   69,  292,  295,  290,
       69,  299,  301,  298,  291,  293,  288,   69,  276,   69,
      294,  290,  292,  295,  321,  299,  296,  290,  300,  301,
      276,  301,  297,  299,  299,  295,  299,  301,  321,  304,

      297,  305,  297,   69,  273,  271,  306,  301,  302,  305,
      279,  305,  305,  305,  274,  299,  303,  276,  290,  301,
      301,  292,  305,  307,  281,  295,  297,  285,  271,  308,
      273,  292,  279,  318,  134,   69,   69,  312,  302,  310,
      309,  325,  324,  323,   69,  311,  299,   69,   69,   69,
      313,  285,  320,  287,  314,  297,  279,  315,  322,  316,
      271,  292,  323,  319,  325,  325,  321,   69,  326,  317,
      325,  327,   69,   69,  329,  332,  332,  323,  327,  334,
      319,  327,  329,  327,  333,  329,  331,   69,  336,  328,
       69,  332,  332,  330,  338,  338,  336,  329,  334,  342,

      337,   69,  332,  334,  338,  334,  334,  336,  334,  335,
       69,  323,  342,  323,  338,  339,  336,  336,  341,  342,
      338,  332,  338,  321,  340,  334,  325,  334,  325,  338,
      323,  342,  343,  332,  321,  318,  134,  344,  327,  342,
      134,  352,  338,   69,  354,   69,   69,  357,  346,  345,
      352,  325,  342,  325,   69,   69,  338,  347,  353,  357,
      332,  354,  321,  342,  351,  319,  327,  350,  348,   69,
      354,  359,  356,  352,  361,  354,  349,  358,  352,  359,
      360,   69,  319,  361,  357,  359,  350,  355,  359,  361,
      361,  357,  354,  361,  134,  363,  359,   69,   69,  361,

      359,  363,  364,  357,  362,  371,   69,  357,  365,  367,
      352,  363,  363,  361,  371,  354,   69,  369,  370,  366,
      357,  371,  373,  352,  359,  363,   69,  371,  375,   69,
      371,  377,  368,  372,  377,  373,  375,  374,  134,  373,
      369,  377,  377,  371,  377,  377,  373,  375,  375,  376,
       69,  383,  379,  385,  373,  378,  375,  377,  371,  377,
       69,  383,  385,  134,  381,  134,  385,  380,  385,   69,
      382,  384,  385,  390,  391,  383,   69,  383,  390,  391,
      383,  385,   69,  269,  381,  386,  268,  386,  267,  113,
      385,   69,  387,   69,   69,  145,  144,  208,  134,  388,

      131,  123,   69,   69,   69,   69,  392,  145,  144,  388,
      140,  387,   49,   49,   49,   54,   54,   54,   69,   69,
      110,  110,  110,  127,  127,  127,  130,  130,  130,  132,
      132,  132,  143,  143,  143,  189,  189,  189,  389,  389,
      389,  137,  131,   52,  123,   69,   76,   75,   71,   70,
       58,   57,   53,   52,  392,    5,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392
    } ;

static const flex_int16_t yy_chk[1007] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   11,   21,   22,   23,   11,   23,   21,   22,
        3,    4,   61,   21,   21,   27,   27,   27,   21,   32,
       31,   33,   34,   36,   61,   35,   21,   39,   37,   34,
       32,   68,   38,   68,   39,   31,   33,   35,   33,   37,
       34,   36,   11,   31,   38,   34,   42,   39,   40,   32,

       31,   33,   34,   36,   41,   35,   43,   39,   37,   40,
       58,   58,   38,   44,   42,   41,   42,   44,   51,   79,
       43,   54,   87,   51,   59,   54,   42,   82,   40,   55,
       55,   55,   56,   62,   41,   56,   43,   59,   58,   56,
       79,   95,   87,   62,   80,   82,   95,  396,   80,   79,
       64,  389,   87,   44,   44,   47,   83,   58,   80,   47,
       47,   54,   47,   47,   81,   47,   47,   80,   47,   64,
       64,   47,   64,   78,   88,   56,   81,   83,   47,   84,
       78,   85,   64,   86,   78,   89,   83,   89,   92,   84,
       89,   88,   85,   93,   81,   94,   98,   92,   86,  101,

       89,   85,  103,   78,   88,   99,  100,  102,  106,   84,
      100,  108,  100,   86,   93,  102,   98,  219,   92,   99,
       94,  101,  100,   99,  103,   94,   98,  107,  104,  101,
      219,  106,  103,  108,  107,   99,  104,  109,  106,  110,
      118,  108,  111,  110,  112,  109,  111,  112,  114,  115,
      117,  112,  120,  114,  117,  119,  120,  240,  155,  115,
      118,  120,  115,  114,  117,  121,  119,  115,  120,  121,
      124,  240,  152,  117,  155,  124,  119,  127,  121,  110,
      110,  127,  111,  111,  384,  169,  135,  112,  112,  122,
      138,  122,  122,  122,  122,  152,  122,  122,  138,  122,

      122,  136,  122,  122,  122,  122,  129,  122,  169,  129,
      133,  133,  122,  129,  128,  128,  128,  127,  128,  135,
      146,  136,  128,  142,  147,  148,  150,  151,  162,  149,
      153,  147,  135,  382,  150,  142,  151,  162,  133,  148,
      177,  146,  154,  157,  153,  153,  177,  142,  148,  129,
      146,  149,  156,  153,  147,  142,  154,  133,  128,  149,
      166,  158,  157,  156,  159,  372,  161,  159,  370,  159,
      158,  168,  154,  158,  160,  158,  160,  160,  168,  160,
      159,  166,  156,  165,  173,  159,  158,  161,  167,  175,
      160,  158,  165,  174,  178,  160,  161,  172,  175,  176,

      167,  168,  185,  180,  172,  181,  360,  173,  179,  167,
      179,  184,  181,  165,  176,  178,  186,  174,  187,  175,
      176,  185,  184,  174,  189,  179,  180,  172,  189,  186,
      190,  179,  197,  180,  190,  187,  191,  193,  194,  191,
      195,  184,  202,  191,  192,  194,  186,  338,  192,  195,
      200,  193,  202,  196,  338,  197,  195,  196,  201,  202,
      193,  199,  213,  205,  189,  189,  198,  196,  198,  201,
      190,  190,  213,  200,  199,  230,  196,  201,  210,  191,
      191,  198,  199,  353,  192,  192,  341,  198,  203,  205,
      203,  230,  203,  203,  203,  203,  204,  212,  211,  210,

      204,  215,  203,  203,  203,  203,  203,  211,  210,  205,
      222,  203,  214,  214,  216,  218,  223,  212,  217,  215,
      217,  217,  214,  224,  225,  222,  216,  212,  276,  326,
      217,  215,  218,  227,  223,  224,  204,  228,  225,  229,
      222,  226,  276,  226,  226,  218,  223,  226,  227,  228,
      233,  232,  234,  224,  225,  235,  236,  229,  231,  226,
      231,  231,  232,  235,  231,  237,  241,  236,  238,  233,
      239,  242,  244,  241,  234,  236,  231,  243,  258,  247,
      237,  232,  234,  238,  277,  245,  239,  253,  243,  245,
      258,  244,  253,  246,  242,  237,  241,  246,  277,  247,

      239,  248,  246,  322,  255,  255,  253,  243,  245,  247,
      254,  248,  259,  254,  255,  256,  246,  257,  264,  256,
      261,  257,  259,  254,  261,  260,  260,  263,  264,  257,
      260,  261,  263,  266,  266,  280,  275,  264,  256,  261,
      260,  281,  280,  279,  320,  263,  265,  278,  282,  294,
      265,  265,  275,  265,  265,  265,  265,  265,  278,  265,
      265,  265,  279,  266,  281,  280,  275,  286,  282,  265,
      288,  283,  291,  296,  287,  292,  293,  278,  282,  297,
      266,  283,  287,  288,  296,  288,  291,  298,  299,  286,
      300,  292,  293,  288,  301,  302,  299,  286,  297,  305,

      300,  304,  291,  296,  303,  303,  306,  302,  309,  298,
      289,  311,  305,  307,  301,  302,  303,  298,  304,  307,
      300,  308,  313,  308,  303,  306,  310,  309,  314,  310,
      311,  304,  307,  310,  315,  318,  318,  308,  315,  316,
      319,  325,  313,  324,  329,  328,  284,  332,  315,  310,
      325,  314,  316,  317,  331,  333,  317,  317,  328,  332,
      317,  329,  317,  317,  324,  318,  317,  319,  317,  335,
      330,  334,  331,  324,  336,  328,  317,  333,  330,  334,
      335,  337,  318,  339,  331,  333,  319,  330,  347,  340,
      348,  344,  348,  336,  350,  339,  347,  351,  272,  335,

      340,  340,  339,  344,  337,  352,  270,  345,  340,  348,
      345,  337,  345,  349,  352,  349,  356,  350,  351,  345,
      349,  355,  357,  349,  349,  349,  358,  351,  359,  362,
      355,  363,  349,  356,  364,  357,  365,  358,  369,  366,
      350,  363,  366,  366,  364,  365,  356,  359,  368,  362,
      374,  375,  366,  377,  368,  365,  358,  368,  368,  362,
      376,  375,  379,  387,  369,  381,  378,  368,  380,  251,
      374,  376,  377,  388,  388,  378,  249,  380,  390,  390,
      374,  379,  220,  209,  369,  378,  207,  380,  206,  188,
      376,  182,  381,  170,  163,  145,  143,  139,  132,  387,

      130,  123,  105,   96,   90,   77,   69,   67,   66,  387,
       63,  381,  393,  393,  393,  394,  394,  394,  395,  395,
      397,  397,  397,  398,  398,  398,  399,  399,  399,  400,
      400,  400,  401,  401,  401,  402,  402,  402,  403,  403,
      403,   60,   57,   52,   50,   30,   29,   28,   26,   24,
       17,   14,   10,    7,    5,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dBaseDSLwin32.l"
#line 2 "dBaseDSLwin32.l"
// ----------------------------------------------------------------------------
// File   : dbaseDSLwin32.l
// Author : Jens Kallup (c) 2023-07.01
// License: all rights reserved.
// ----------------------------------------------------------------------------
# include "../common.h"
# include "dBaseDSLwin32.tab.h"

int count(void);
void* addTextPtr;

int yy_col = 1;
int yy_row = 1;

int        yy_dbase_win32_count(void)        { return yy_row; }
int EXPORT yy_dbase_win32_lex_get_line(void) { return yy_dbase_win32_count(); }
int EXPORT yy_dbase_win32_lex_getlines(void) { return yy_dbase_win32_count(); }

char* data_code;
char* data_text;
char* data_data;

#line 818 "lex.yy.c"

#line 820 "lex.yy.c"

#define INITIAL 0
#define Comment1 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 64 "dBaseDSLwin32.l"


#line 1041 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 393 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 956 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 67 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 70 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "dBaseDSLwin32.l"
{
    header_isok = 1;
    node_head   = (struct node*) malloc( sizeof( struct node ) );
    BEGIN(INITIAL);
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 77 "dBaseDSLwin32.l"
{
    header_isok = 1;
    node_head   = (struct node*) malloc( sizeof( struct node ) );
    BEGIN(INITIAL);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 84 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 86 "dBaseDSLwin32.l"
{ BEGIN(Comment1); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 87 "dBaseDSLwin32.l"
{ yy_row += 1;     yy_row++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "dBaseDSLwin32.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "dBaseDSLwin32.l"
{ /* empty */ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 91 "dBaseDSLwin32.l"
{ yy_col = 1;      yy_row++; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "dBaseDSLwin32.l"
{
    if (header_isok != 1)
    yyerror("no header available !");
    return TOK_CLASS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "dBaseDSLwin32.l"
{ return TOK_CLEAR;     }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 99 "dBaseDSLwin32.l"
{ return TOK_CUSTOM;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 100 "dBaseDSLwin32.l"
{ return TOK_DEFINE;    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 101 "dBaseDSLwin32.l"
{ return TOK_ELSE;      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 102 "dBaseDSLwin32.l"
{ return TOK_ENDCLASS;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 103 "dBaseDSLwin32.l"
{ return TOK_ENDFOR;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 104 "dBaseDSLwin32.l"
{ return TOK_ENDIF;     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 105 "dBaseDSLwin32.l"
{ return TOK_ENDWITH;   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 106 "dBaseDSLwin32.l"
{ return TOK_FALSE;     }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 107 "dBaseDSLwin32.l"
{ return TOK_FOR;       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 108 "dBaseDSLwin32.l"
{ return TOK_FUNCTION;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 109 "dBaseDSLwin32.l"
{ return TOK_IF;        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 110 "dBaseDSLwin32.l"
{ return TOK_LOCAL;     }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 111 "dBaseDSLwin32.l"
{ return TOK_NEW;       }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 112 "dBaseDSLwin32.l"
{ return TOK_OF;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 113 "dBaseDSLwin32.l"
{ return TOK_PARAMETER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 114 "dBaseDSLwin32.l"
{ return TOK_PRIVATE;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 115 "dBaseDSLwin32.l"
{ return TOK_PROCEDURE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 116 "dBaseDSLwin32.l"
{ return TOK_RETURN;    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 117 "dBaseDSLwin32.l"
{ return TOK_SET;       }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 118 "dBaseDSLwin32.l"
{ return TOK_TO;        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 119 "dBaseDSLwin32.l"
{ return TOK_TRUE;      }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 120 "dBaseDSLwin32.l"
{ return TOK_WITH;      }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 122 "dBaseDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 123 "dBaseDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 125 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for: identifier's ...
	// -----------------------------------
	yylval.node_and_value.name = (char*) malloc( strlen( yytext ) + 1); strcpy(
	yylval.node_and_value.name, yytext);
	
	return TOK_ID;
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 135 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for: "Hello World"
	// pattern for: 'Hello World'
	// -----------------------------------
	yylval.node_and_value.content_str = (char*) malloc( strlen( yytext ) + 1); strcpy(
    yylval.node_and_value.content_str, yytext ) ;

	return TOK_STRING;
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 145 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for: "Hello World"
	// pattern for: 'Hello World'
	// -----------------------------------
	yylval.node_and_value.content_str = (char*) malloc( strlen( yytext ) + 1); strcpy(
    yylval.node_and_value.content_str, yytext ) ;

	return TOK_STRING;
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 156 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for:  [ "Hallo \" World" ]
	// pattern for:  [ 'Hello \' World' ]
	// -----------------------------------
	char* str = yytext;
	int   len = 0;
	
	if (str[0] == '\'' || str[0] == '\"')
		str++;
		
	len = strlen(str);
	
	if (str[len - 1] == '\'' || str[len - 1] == '\"')
		str[len - 1] =  '\0' ;
	
	yylval.node_and_value.name = (char*) malloc( strlen( str ) + 1); strcpy(
	yylval.node_and_value.name, str );
	
	return TOK_STRING_BRACE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 178 "dBaseDSLwin32.l"
{ return TOK_AND;    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 179 "dBaseDSLwin32.l"
{ return TOK_NOT;    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 180 "dBaseDSLwin32.l"
{ return TOK_OR;     }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 182 "dBaseDSLwin32.l"
{ return TOK_FALSE;  }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 183 "dBaseDSLwin32.l"
{ return TOK_TRUE;   }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 185 "dBaseDSLwin32.l"
{ return TOK_EQEQ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 186 "dBaseDSLwin32.l"
{ return TOK_LTGT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 187 "dBaseDSLwin32.l"
{ return TOK_EQGT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 188 "dBaseDSLwin32.l"
{ return TOK_EQLT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 189 "dBaseDSLwin32.l"
{ return TOK_LTEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 190 "dBaseDSLwin32.l"
{ return TOK_GTEQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 192 "dBaseDSLwin32.l"
{ return TOK_PRINT_TWO; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 194 "dBaseDSLwin32.l"
{ return ':'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 195 "dBaseDSLwin32.l"
{ return ';'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 196 "dBaseDSLwin32.l"
{ return '-'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 197 "dBaseDSLwin32.l"
{ return '+'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 198 "dBaseDSLwin32.l"
{ return '*'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 199 "dBaseDSLwin32.l"
{ return '/'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 200 "dBaseDSLwin32.l"
{ return '%'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 202 "dBaseDSLwin32.l"
{ return '#'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 204 "dBaseDSLwin32.l"
{ return TOK_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 206 "dBaseDSLwin32.l"
{ return '('; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 207 "dBaseDSLwin32.l"
{ return ')'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 208 "dBaseDSLwin32.l"
{ return '['; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 209 "dBaseDSLwin32.l"
{ return ']'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 210 "dBaseDSLwin32.l"
{ return '{'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 211 "dBaseDSLwin32.l"
{ return '}'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 212 "dBaseDSLwin32.l"
{ return ','; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 213 "dBaseDSLwin32.l"
{ return '.'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 215 "dBaseDSLwin32.l"
{ return TOK_PRINT_ONE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 217 "dBaseDSLwin32.l"
{
    char buffer[200];
    std::sprintf( buffer, "Unrecognized character: %s\n", yytext );
    yyerror(buffer);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
#line 223 "dBaseDSLwin32.l"
{ return TOK_YYEOF; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 224 "dBaseDSLwin32.l"
ECHO;
	YY_BREAK
#line 1549 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 393 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 393 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 392);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "dBaseDSLwin32.l"


int yywrap(void) { return 1; }

void yyerror(const char* m)
{
	char * buffer = (char *) malloc(1024);
	char * number = (char *) malloc( 255);
	
	itoa(yy_row,number,10);
	
	strcpy( buffer, "error in line: ");
	strcat( buffer, number);
	strcat( buffer, ": ");
	strcat( buffer, m);

	ShowParserErrorText( buffer );
}

BOOL EXPORT
yy_dbase_win32_lex_main(
    char* filename,
    char* tempDir )
{
    BOOL   result = FALSE;
    char * buffer;

    // ------------------------------------------
    // try to open file, saved before ...
    // ------------------------------------------
    if (!(yyin = fopen(filename,"r"))) {
        buffer = (char*) malloc(100);

        std::sprintf(buffer, "could not open file: %s", filename);
        ShowParserErrorText(buffer);

        free(buffer);
        return false;
    }

    yy_row = 1;
    yy_col = 1;

	// ------------------------------------------
	// start the race run ...
	// ------------------------------------------
	node_head        = (struct node *) malloc( sizeof( struct node ) );
	node_new         = (struct node *) malloc( sizeof( struct node ) ); // dummy to point head itself
	node_head->token = (       char *) malloc( 8 );
	strcpy( node_head->token, "root" );

	// ------------------------
	// root/first record item
	// ------------------------
	node_new->prev = node_head;
	node_new->next = NULL;
	
	// ------------------------
	// call parser ...
	// ------------------------
	result = yyparse();
	
	fclose(yyin);
	return result;
}

void EXPORT
yy_dbase_win32_lex_close(void) {
    fclose(yyin);
}


