
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[389] =
    {   0,
       12,   12,   10,   10,   73,   71,   12,   13,   13,   71,
       71,   61,   60,   71,   63,   64,   58,   57,   69,   56,
       70,   59,   38,   54,   55,   71,   62,   71,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   65,   66,   67,   13,   68,   72,   10,   72,
       12,   49,    0,   41,    0,    3,    7,    0,    0,    0,
        0,    0,    0,    9,    1,    0,   38,   40,   62,   52,
       51,   48,   50,   53,   40,   40,   40,    0,   40,    0,
       40,   40,    0,   40,   40,   40,    0,   26,   26,   40,
        0,   40,    0,   29,   29,   40,   40,    0,   40,    0,

       40,    0,   35,   40,   35,   40,    0,    0,    0,    0,
       42,    0,    0,   26,    0,    0,   35,    0,    0,   26,
       10,    0,   11,    0,   41,    0,    3,    4,    7,    7,
        8,    7,    0,   46,    0,    0,   47,   46,    0,    1,
        2,   39,   40,   40,    0,   40,    0,    0,    0,    0,
       40,    0,   40,    0,   40,    0,    0,   40,    0,   24,
       24,   40,    0,   24,   40,    0,   28,   28,   40,    0,
       40,   40,    0,    0,    0,    0,   40,    0,   34,   34,
       40,    0,   40,    0,    0,    0,    0,    0,   42,    0,
       34,   28,    0,   24,    0,    0,   24,    0,   34,   24,

        7,    0,    0,   45,    0,   40,    0,   40,    0,    0,
       40,    0,    0,   40,    0,   18,   18,   40,   40,   40,
       40,    0,    0,    0,    0,    0,   18,   40,    0,   40,
        0,    0,   40,    0,   40,    0,   40,    0,   40,    0,
        0,    0,   40,    0,   36,   36,   37,   37,    0,    0,
       18,   36,    0,   18,   37,    0,    0,   18,    0,    0,
       18,    7,   43,   44,   43,   14,   14,   15,   15,   14,
       40,    0,   14,   40,    0,   40,    0,   40,    0,   21,
       21,   40,    0,   21,   23,   23,   40,    0,   23,   27,
       27,   40,    0,   40,    0,   40,    0,    0,    0,   40,

        0,   23,    0,    0,   15,    0,   21,   14,   23,   27,
        0,   15,   14,    7,    7,   16,   16,   17,   17,   40,
        0,   20,   20,   40,    0,   20,   40,    0,   40,    0,
       40,    0,   40,    0,    0,    0,   33,   33,   17,   16,
        0,   16,   17,    0,   16,    7,   40,    0,   22,   22,
       22,   40,    0,   40,    0,   31,   31,   40,    0,   31,
       31,    0,   22,   22,    7,   19,   19,   25,   25,   40,
        0,   40,    0,    0,   19,   19,    7,   30,   30,   32,
       32,   30,    7,    5,    5,    5,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       26,   31,   32,   26,   26,   33,   34,   35,   36,   37,
       26,   38,   39,   40,   41,   42,   43,   26,   26,   26,
       44,   45,   46,    1,   26,    1,   25,   26,   27,   28,

       29,   30,   26,   31,   32,   26,   26,   33,   34,   35,
       36,   37,   26,   38,   39,   40,   41,   42,   43,   26,
       26,   26,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[400] =
    {   0,
        0,    0,   47,   48,  913,  945,  910,  945,  945,  888,
       46,  945,  945,  901,  945,  945,  896,  945,  945,  945,
       28,   41,   38,  885,  945,  884,   43,  883,  885,   51,
       50,   52,   53,   56,   54,   64,   58,   78,   76,   88,
       77,   89,  104,  945,  945,  126,  945,  945,  900,  105,
      900,  945,  121,  945,  132,  898,  117,   74,  883,   26,
       91,  882,  135,  945,  895,  878,   63,  879,  945,  945,
      945,  945,  945,  945,  875,  115,  109,  143,  150,  130,
      156,  157,  151,  167,  165,  162,  154,  874,  945,  169,
       84,  175,  158,  873,  945,  174,  188,  189,  190,   93,

      192,  105,  872,  200,  106,  195,  168,  223,  236,  241,
      945,  201,  215,  945,  225,  224,  229,  230,  222,  263,
      887,  213,  945,  269,  270,  302,  886,  945,  885,  281,
      945,  282,  246,  945,  249,  869,  945,  945,  292,  882,
      945,  862,  288,  294,  296,  297,  278,  283,  275,  309,
      306,  307,  314,  312,  331,  337,  341,  327,  317,  860,
      945,  359,  324,  349,  334,  352,  859,  945,  362,  358,
      371,  372,  366,  211,  367,  376,  385,  354,  857,  945,
      392,  369,  397,  361,  826,  417,  419,  428,  426,  405,
      364,  407,  412,  410,  427,  419,  418,  428,  439,  463,

      449,  830,  825,  945,  816,  459,  443,  462,  441,  470,
      465,  413,  476,  497,   95,  796,  945,  498,  500,  503,
      502,  493,  487,  491,  507,  451,  524,  511,  499,  523,
      402,  529,  519,  516,  534,  527,  551,  518,  554,  533,
      549,  555,  560,  448,  790,  945,  764,  945,  556,  553,
      548,  580,  570,  559,  573,  579,  586,  945,  590,  585,
      614,  620,  945,  945,  945,  727,  945,  655,  945,  945,
      597,  607,  608,  611,  628,  610,  612,  642,  625,  617,
      945,  645,  552,  641,  613,  945,  646,  635,  638,  546,
      945,  653,  640,  652,  647,  656,  649,  663,  670,  677,

      667,  676,  678,  674,  680,  689,  687,  945,  691,  695,
      693,  688,  719,  727,  731,  525,  945,  466,  945,  713,
      694,  428,  945,  737,  707,  732,  726,  728,  730,  725,
      721,  743,  747,  736,  752,  757,  403,  945,  945,  746,
      751,  945,  756,  772,  777,  786,  783,  771,  377,  945,
      773,  788,  779,  809,  795,  333,  945,  807,  791,  792,
      803,  811,  945,  823,  832,  309,  945,  305,  945,  818,
      806,  834,  819,  835,  836,  839,  866,  246,  945,  241,
      945,  945,  867,  591,  225,  872,  945,  945,  915,  918,
      920,   78,  923,  926,  929,  932,  935,  938,  941

    } ;

static const flex_int16_t yy_def[400] =
    {   0,
      388,    1,  389,  389,  388,  388,  388,  388,  388,  388,
      390,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  391,  388,  388,  388,  388,  388,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  393,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  390,  388,  394,  395,  396,  388,  388,  388,
      388,  388,  388,  388,  397,  388,  391,  391,  388,  388,
      388,  388,  388,  388,  392,  392,  392,  388,  392,  388,
      392,  392,  388,  392,  392,  392,  388,  392,  388,  392,
      388,  392,  388,  392,  388,  392,  392,  388,  392,  388,

      392,  388,  392,  392,  388,  392,  388,  393,  393,  398,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  390,  390,  394,  395,  388,  396,  396,
      388,  396,  388,  388,  388,  388,  388,  388,  388,  397,
      388,  388,  392,  392,  388,  392,  388,  388,  388,  388,
      392,  388,  392,  388,  392,  388,  388,  392,  388,  392,
      388,  392,  388,  388,  392,  388,  392,  388,  392,  388,
      392,  392,  388,  388,  388,  388,  392,  388,  392,  388,
      392,  388,  392,  388,  388,  393,  393,  398,  393,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,

      396,  388,  388,  388,  388,  392,  388,  392,  388,  388,
      392,  388,  388,  392,  388,  392,  388,  392,  392,  392,
      392,  388,  388,  388,  388,  388,  388,  392,  388,  392,
      388,  388,  392,  388,  392,  388,  392,  388,  392,  388,
      388,  388,  392,  388,  392,  388,  392,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  396,  388,  388,  388,  392,  388,  392,  388,  388,
      392,  388,  388,  392,  388,  392,  388,  392,  388,  392,
      388,  392,  388,  388,  392,  388,  392,  388,  388,  392,
      388,  392,  388,  392,  388,  392,  388,  388,  388,  392,

      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  396,  396,  392,  388,  392,  388,  392,
      388,  392,  388,  392,  388,  388,  392,  388,  392,  388,
      392,  388,  392,  388,  388,  388,  392,  388,  388,  388,
      388,  388,  388,  388,  388,  396,  392,  388,  392,  388,
      388,  392,  388,  392,  388,  392,  388,  392,  388,  388,
      388,  388,  388,  388,  396,  392,  388,  392,  388,  392,
      388,  392,  388,  388,  388,  388,  396,  392,  388,  392,
      388,  388,  396,  399,  399,  399,  388,    0,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388

    } ;

static const flex_int16_t yy_nxt[995] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   11,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   30,   31,   32,   33,
       29,   34,   35,   29,   36,   37,   38,   39,   40,   41,
       29,   29,   42,   43,    6,   44,   45,   46,   47,   49,
       49,   54,   58,   64,   66,   54,   67,   59,   65,   50,
       50,  135,   60,   61,   71,   72,   73,   62,   68,   68,
       68,   68,   68,  135,   68,   63,   68,   84,   79,   66,
       75,   67,   68,   76,   81,   88,   82,   94,   85,   90,
       55,   77,   92,   86,   68,   68,   68,   80,   78,   83,

       87,   91,   96,   89,   99,   95,   68,   68,  133,  109,
      166,   93,  103,  109,  104,   97,  101,  122,  130,  131,
      106,  133,  123,  100,  105,   98,   54,   68,  136,  275,
       54,  166,  178,   68,   53,  102,  107,  125,  136,  143,
      178,  125,  275,  144,  180,  132,  182,  146,  110,  111,
      112,  138,  180,  182,  113,  114,  147,  107,  115,  152,
      116,  117,  145,  118,  132,   55,  119,  148,   68,  133,
      135,  149,  136,  120,   68,   68,  126,  152,  156,  151,
       68,  147,  139,   68,  155,   68,  159,   68,  163,  154,
      150,  161,   68,   68,  153,  165,  162,  152,  157,  158,

      168,  164,  160,  154,  156,  168,   68,  184,   68,  163,
       68,  169,  161,   68,  159,  184,  166,  167,   68,  171,
      174,  170,  168,  172,  175,  122,  170,  387,  185,  177,
      123,  179,  185,  159,  183,  173,  176,  178,  170,  180,
      181,  185,  184,  108,  152,  185,  187,  182,  190,  148,
      187,  156,  238,  149,  191,  166,  163,  168,  238,   68,
      147,  174,  192,  154,   68,  175,  161,  110,  111,  196,
      182,  156,  193,  202,   54,   54,  194,  195,   54,   54,
      110,  111,  130,  131,  131,  188,  189,  148,  203,  166,
      156,  149,  152,  202,  174,  159,  203,  163,  175,  209,

      197,  198,  199,  182,   53,  168,   68,  125,  204,  132,
      200,  125,   68,   55,   55,   68,  201,  212,  208,  202,
      209,  207,  209,   68,   68,  212,  206,   68,  132,  201,
      207,  203,   68,  209,  207,  207,  211,  214,  215,  205,
      217,  209,  216,  210,  212,   68,  126,  207,  212,   68,
      231,   68,   68,  215,  215,  229,  213,  218,  233,  217,
      219,  217,  220,  223,  229,  228,  224,  223,  225,  217,
      224,  231,  225,  221,  229,  231,  234,   68,  222,  226,
       68,  234,  236,  226,  222,  230,  235,  229,  227,   68,
       68,  248,  240,  240,  244,   68,  232,  246,  239,  234,

      236,  244,  240,   68,  244,  236,  231,  238,  248,  236,
       68,  244,  237,  241,  240,   68,  246,  238,  238,  240,
      245,   68,  185,  242,  185,  243,  185,  247,  185,  236,
      108,  185,  244,  187,  234,  185,  209,  187,  215,  246,
      217,  288,  236,  229,  248,  231,   68,  244,  272,  288,
      207,  131,  249,  240,  250,  246,  217,  234,  212,  251,
      272,  110,  111,  110,  111,  236,  253,  212,  238,  248,
      110,  111,  188,  189,  252,  254,  262,   68,  269,  244,
       68,  267,  283,   68,   68,  301,  255,  256,  269,  257,
      267,  258,  224,  248,  259,  301,  262,  266,  283,  268,

      271,  260,  212,  244,  238,  226,  267,  269,  267,  269,
      261,  272,  272,  269,  267,   68,   68,  270,   68,  277,
       68,   68,  281,  273,  283,  277,  279,  286,  279,   68,
      276,  274,  280,  282,  277,  278,  281,   68,  279,  285,
      284,   68,  295,   68,  275,  277,  286,  279,  291,  283,
      281,  290,   68,  281,  281,  283,  277,  286,  286,  279,
      293,  297,  287,  291,   68,  295,  291,  292,  288,   68,
      288,  284,   68,  295,  293,  294,  289,  297,   68,  295,
      297,  293,  296,  297,  286,  269,  267,  275,  293,  293,
      301,  325,  386,  387,  272,  270,  298,  300,  295,  325,

      303,  297,  299,  302,  295,  272,  272,  301,  297,  288,
      301,  291,  293,  286,  297,   68,  269,  304,  277,  281,
      301,  314,  131,  267,  275,  288,  305,  298,   68,   68,
      316,   68,  308,  306,  320,   68,  321,  307,  295,  318,
      317,  317,  309,  281,  317,  283,  310,  293,  275,  311,
      315,  312,  267,  288,  317,  317,  319,  321,  319,  321,
       68,  313,  323,   68,   68,  321,  328,  315,  330,  328,
       68,   68,  323,   68,   68,  319,  334,  327,  323,  322,
      325,  329,  328,  333,  324,  328,  332,  330,  326,  323,
      334,  331,  325,  328,  332,   68,  334,  334,  330,  332,

      330,  338,  332,  334,  330,  328,  319,  317,  330,  332,
      335,  337,  338,  321,  338,  319,  334,  336,  334,  321,
      328,  340,  338,  330,  338,  339,  317,  330,  314,  131,
      323,   68,  348,  131,  319,  338,  341,  350,  334,   68,
      342,  348,  321,  321,   68,   68,  334,  343,   68,  356,
      328,  347,  317,  338,  350,   68,  323,  315,  344,  346,
      348,  352,  350,  353,  355,   68,  345,  349,  357,  354,
      348,  357,  355,  353,  315,  353,  359,  355,  346,  351,
      357,  353,   68,  359,  350,  357,  353,  358,  131,  348,
      357,  359,  359,  353,  359,  355,  355,  359,  362,  360,

      357,   68,  350,  355,  361,  357,   68,  350,   68,  367,
      365,  367,  353,  369,   68,  348,  355,  359,  367,  363,
      367,  366,  368,  371,  364,   68,  369,   68,  373,  373,
      367,  371,  265,  365,  131,  369,   68,  370,  373,  373,
      373,  264,  371,  379,  372,  369,  263,  381,  373,  367,
      374,  371,   68,  379,  373,  378,  371,  369,  375,  377,
      373,  367,  380,  381,  381,  379,  381,  381,  131,  131,
      376,  111,  379,  386,  387,   68,  379,   68,   68,  377,
      142,  381,  382,  381,  141,  204,  382,  131,  128,  121,
       68,   68,   68,   68,  383,  388,  142,  141,  137,  134,

      128,   51,  121,   68,  384,   74,   70,   69,   57,   56,
       52,   51,  388,  383,  384,   48,   48,   48,   53,   53,
       53,   68,   68,  108,  108,  108,  124,  124,  124,  127,
      127,  127,  129,  129,  129,  140,  140,  140,  186,  186,
      186,  385,  385,  385,    5,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388

    } ;

static const flex_int16_t yy_chk[995] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   11,   21,   22,   23,   11,   23,   21,   22,    3,
        4,   60,   21,   21,   27,   27,   27,   21,   31,   30,
       32,   33,   35,   60,   34,   21,   37,   33,   31,   67,
      392,   67,   36,   30,   32,   34,   32,   37,   33,   35,
       11,   30,   36,   33,   39,   41,   38,   31,   30,   32,

       33,   35,   38,   34,   39,   37,   40,   42,   58,   43,
       91,   36,   41,   43,   41,   38,   40,   50,   57,   57,
       42,   58,   50,   39,   41,   38,   53,   77,   61,  215,
       53,   91,  100,   76,   55,   40,   42,   55,   61,   76,
      100,   55,  215,   76,  102,   57,  105,   77,   43,   43,
       46,   63,  102,  105,   46,   46,   77,   46,   46,   80,
       46,   46,   76,   46,   57,   53,   46,   78,   79,   63,
       63,   78,   63,   46,   81,   82,   55,   80,   83,   79,
       86,   78,   63,   85,   82,   84,   87,   90,   87,   83,
       78,   87,   96,   92,   81,   90,   86,   79,   83,   84,

       93,   87,   85,   81,   82,   93,   97,  107,   99,   86,
      101,   96,   85,  106,   84,  107,   90,   92,  104,   97,
       98,   96,   92,   97,   98,  122,   98,  385,  108,   99,
      122,  101,  108,  112,  106,   97,   98,   99,  112,  101,
      104,  109,  106,  110,  113,  109,  110,  104,  112,  115,
      110,  116,  174,  115,  113,  117,  119,  113,  174,  380,
      119,  118,  113,  115,  378,  118,  117,  108,  108,  119,
      118,  116,  115,  133,  124,  125,  117,  118,  124,  125,
      109,  109,  130,  130,  132,  110,  110,  120,  135,  120,
      120,  120,  120,  133,  120,  120,  135,  120,  120,  149,

      120,  120,  120,  120,  126,  120,  143,  126,  139,  130,
      120,  126,  144,  124,  125,  146,  132,  147,  144,  139,
      145,  148,  149,  368,  151,  147,  143,  366,  130,  132,
      148,  139,  153,  150,  145,  143,  146,  151,  152,  139,
      154,  144,  153,  145,  146,  158,  126,  150,  150,  155,
      163,  356,  165,  151,  152,  159,  150,  155,  165,  154,
      155,  153,  155,  156,  159,  158,  156,  157,  156,  157,
      157,  163,  157,  155,  158,  164,  166,  162,  155,  156,
      169,  165,  170,  157,  156,  162,  169,  164,  157,  171,
      172,  184,  173,  175,  178,  349,  164,  182,  172,  166,

      176,  178,  176,  177,  191,  170,  162,  173,  184,  169,
      181,  191,  171,  173,  175,  183,  182,  176,  171,  172,
      181,  337,  186,  176,  187,  177,  186,  183,  187,  190,
      188,  189,  177,  188,  194,  189,  193,  188,  192,  181,
      193,  231,  197,  190,  183,  196,  322,  192,  212,  231,
      193,  201,  190,  195,  192,  195,  198,  194,  196,  193,
      212,  186,  186,  187,  187,  197,  196,  198,  195,  199,
      189,  189,  188,  188,  195,  198,  201,  206,  209,  199,
      208,  207,  226,  211,  318,  244,  199,  200,  209,  200,
      207,  200,  200,  200,  200,  244,  201,  206,  226,  208,

      211,  200,  200,  200,  200,  200,  206,  210,  210,  208,
      200,  213,  211,  213,  213,  214,  218,  210,  219,  223,
      221,  220,  222,  213,  222,  222,  224,  229,  222,  228,
      218,  214,  220,  221,  223,  219,  225,  233,  224,  228,
      222,  230,  238,  316,  214,  218,  229,  219,  234,  221,
      220,  233,  235,  227,  225,  227,  227,  232,  228,  227,
      236,  240,  230,  234,  290,  238,  233,  235,  232,  237,
      230,  227,  239,  241,  236,  237,  232,  241,  243,  242,
      240,  235,  239,  242,  249,  251,  251,  250,  242,  249,
      250,  283,  384,  384,  254,  251,  241,  243,  237,  283,

      250,  239,  242,  249,  252,  253,  254,  243,  252,  253,
      255,  256,  256,  260,  257,  271,  256,  253,  257,  259,
      255,  262,  262,  260,  259,  257,  256,  252,  276,  274,
      271,  285,  260,  257,  276,  280,  277,  259,  261,  274,
      272,  273,  261,  261,  271,  261,  261,  261,  261,  261,
      262,  261,  261,  261,  272,  273,  275,  276,  274,  277,
      278,  261,  279,  282,  287,  284,  288,  262,  293,  289,
      294,  292,  279,  268,  296,  275,  297,  287,  284,  278,
      284,  292,  288,  296,  282,  289,  295,  293,  284,  278,
      298,  294,  282,  287,  295,  300,  297,  299,  299,  294,

      292,  301,  298,  296,  302,  304,  303,  304,  305,  299,
      298,  300,  303,  306,  301,  307,  306,  299,  309,  310,
      306,  304,  312,  302,  300,  303,  311,  305,  314,  314,
      311,  320,  321,  315,  307,  312,  306,  325,  309,  331,
      311,  321,  310,  313,  327,  266,  313,  313,  329,  331,
      313,  320,  313,  313,  325,  324,  313,  314,  313,  315,
      320,  327,  326,  328,  330,  333,  313,  324,  331,  329,
      326,  332,  330,  327,  314,  328,  334,  329,  315,  326,
      335,  340,  247,  334,  324,  336,  341,  333,  346,  341,
      332,  341,  335,  340,  333,  343,  336,  336,  341,  335,

      344,  347,  344,  343,  336,  345,  352,  345,  245,  348,
      346,  351,  345,  353,  216,  345,  345,  345,  348,  344,
      351,  347,  352,  355,  345,  358,  353,  354,  359,  360,
      347,  361,  205,  346,  365,  352,  370,  354,  359,  360,
      361,  203,  355,  371,  358,  362,  202,  373,  362,  362,
      361,  364,  372,  371,  358,  370,  354,  364,  362,  365,
      364,  364,  372,  374,  375,  370,  373,  376,  377,  383,
      364,  185,  374,  386,  386,  179,  376,  167,  160,  365,
      142,  372,  374,  375,  140,  136,  376,  129,  127,  121,
      103,   94,   88,   75,  377,   68,   66,   65,   62,   59,

       56,   51,   49,   29,  383,   28,   26,   24,   17,   14,
       10,    7,    5,  377,  383,  389,  389,  389,  390,  390,
      390,  391,  391,  393,  393,  393,  394,  394,  394,  395,
      395,  395,  396,  396,  396,  397,  397,  397,  398,  398,
      398,  399,  399,  399,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388,  388,  388,  388,  388,  388,  388,
      388,  388,  388,  388

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dBaseDSLwin32.l"
#line 2 "dBaseDSLwin32.l"
// ----------------------------------------------------------------------------
// File   : dbaseDSLwin32.l
// Author : Jens Kallup (c) 2023-07.01
// License: all rights reserved.
// ----------------------------------------------------------------------------
# include "../common.h"
# include "dBaseDSLwin32.tab.h"

// ----------------------------------------------------------------------------
// parser variables and constants:
// ----------------------------------------------------------------------------
typedef void (*addParserErrorText)(const char* message);
static addParserErrorText m_addParserErrorText = NULL;

int count(void);
void* addTextPtr;

int yy_col = 1;
int yy_row = 1;

int        yy_dbase_win32_count(void)        { return yy_row; }
int EXPORT yy_dbase_win32_lex_get_line(void) { return yy_dbase_win32_count(); }
int EXPORT yy_dbase_win32_lex_getlines(void) { return yy_dbase_win32_count(); }

char* data_code;
char* data_text;
char* data_data;

#line 818 "lex.yy.c"

#line 820 "lex.yy.c"

#define INITIAL 0
#define Comment1 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 70 "dBaseDSLwin32.l"


#line 1041 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 389 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 945 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 73 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 76 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "dBaseDSLwin32.l"
{
    header_isok = 1;
    node_head   = (struct node*) malloc( sizeof( struct node ) );
    BEGIN(INITIAL);
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 83 "dBaseDSLwin32.l"
{
    header_isok = 1;
    node_head   = (struct node*) malloc( sizeof( struct node ) );
    BEGIN(INITIAL);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "dBaseDSLwin32.l"
{ /* DO NOTHING */ }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 90 "dBaseDSLwin32.l"
{ /* DO NOTHING */ yy_row++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 92 "dBaseDSLwin32.l"
{ BEGIN(Comment1); }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 93 "dBaseDSLwin32.l"
{ yy_row += 1;     yy_row++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 94 "dBaseDSLwin32.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "dBaseDSLwin32.l"
{ /* empty */ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 97 "dBaseDSLwin32.l"
{ yy_col = 1;      yy_row++; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "dBaseDSLwin32.l"
{
    if (header_isok != 1) {
        yyerror("no header available !");
        return 0;
    }   else {
    /*
        static char dummy = 0;
        data_text =
            "unit A2;\n"
            "interface\n"
            "var Form2: TForm;\n"
            "implementation\n"
            "procedure main;\n"
            "begin\n"
              "Form2 := TForm.Create(Application);\n"
              "Form2.ShowModal;\n"
            "end;\n"
            "end.";
        if (dummy == 1)
    */
    }
    return TOK_CLASS;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "dBaseDSLwin32.l"
{ return TOK_CLEAR;     }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "dBaseDSLwin32.l"
{ return TOK_CUSTOM;    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "dBaseDSLwin32.l"
{ return TOK_DEFINE;    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "dBaseDSLwin32.l"
{ return TOK_ELSE;      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "dBaseDSLwin32.l"
{ return TOK_ENDCLASS;  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 "dBaseDSLwin32.l"
{ return TOK_ENDFOR;    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "dBaseDSLwin32.l"
{ return TOK_ENDIF;     }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 129 "dBaseDSLwin32.l"
{ return TOK_ENDWITH;   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 130 "dBaseDSLwin32.l"
{ return TOK_FALSE;     }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 131 "dBaseDSLwin32.l"
{ return TOK_FOR;       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 132 "dBaseDSLwin32.l"
{ return TOK_FUNCTION;  }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 133 "dBaseDSLwin32.l"
{ return TOK_IF;        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 134 "dBaseDSLwin32.l"
{ return TOK_LOCAL;     }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 135 "dBaseDSLwin32.l"
{ return TOK_NEW;       }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 136 "dBaseDSLwin32.l"
{ return TOK_OF;        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "dBaseDSLwin32.l"
{ return TOK_PARAMETER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 138 "dBaseDSLwin32.l"
{ return TOK_PRIVATE;   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 139 "dBaseDSLwin32.l"
{ return TOK_PROCEDURE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "dBaseDSLwin32.l"
{ return TOK_RETURN;    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "dBaseDSLwin32.l"
{ return TOK_SET;       }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "dBaseDSLwin32.l"
{ return TOK_TO;        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 143 "dBaseDSLwin32.l"
{ return TOK_TRUE;      }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 144 "dBaseDSLwin32.l"
{ return TOK_WITH;      }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 146 "dBaseDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 147 "dBaseDSLwin32.l"
{ yylval.node_and_value.value = atof(yytext); return TOK_NUMBER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for: identifier's ...
	// -----------------------------------
	yylval.node_and_value.name = (char*) malloc( strlen( yytext ) + 1); strcpy(
	yylval.node_and_value.name, yytext);
	
	return TOK_ID;
}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 159 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for: "Hello World"
	// pattern for: 'Hello World'
	// -----------------------------------
	yylval.node_and_value.name = (char*) malloc( strlen( yytext ) + 1); strcpy(
	yylval.node_and_value.name, yytext );
	
	return TOK_STRING;
}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 170 "dBaseDSLwin32.l"
{
	// -----------------------------------
	// pattern for:  [ "Hallo \" World" ]
	// pattern for:  [ 'Hello \' World' ]
	// -----------------------------------
	char* str = yytext;
	int   len = 0;
	
	if (str[0] == '\'' || str[0] == '\"')
		str++;
		
	len = strlen(str);
	
	if (str[len - 1] == '\'' || str[len - 1] == '\"')
		str[len - 1] =  '\0' ;
	
	yylval.node_and_value.name = (char*) malloc( strlen( str ) + 1); strcpy(
	yylval.node_and_value.name, str );
	
	return TOK_STRING_BRACE;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 192 "dBaseDSLwin32.l"
{ return TOK_AND;    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 193 "dBaseDSLwin32.l"
{ return TOK_NOT;    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 194 "dBaseDSLwin32.l"
{ return TOK_OR;     }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 196 "dBaseDSLwin32.l"
{ return TOK_FALSE;  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 197 "dBaseDSLwin32.l"
{ return TOK_TRUE;   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 199 "dBaseDSLwin32.l"
{ return TOK_EQEQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 200 "dBaseDSLwin32.l"
{ return TOK_LTGT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 201 "dBaseDSLwin32.l"
{ return TOK_EQGT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 202 "dBaseDSLwin32.l"
{ return TOK_EQLT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 203 "dBaseDSLwin32.l"
{ return TOK_LTEQ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 204 "dBaseDSLwin32.l"
{ return TOK_GTEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 206 "dBaseDSLwin32.l"
{ return ':'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 207 "dBaseDSLwin32.l"
{ return ';'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 208 "dBaseDSLwin32.l"
{ return '-'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 209 "dBaseDSLwin32.l"
{ return '+'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 210 "dBaseDSLwin32.l"
{ return '*'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 211 "dBaseDSLwin32.l"
{ return '/'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 212 "dBaseDSLwin32.l"
{ return '%'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 214 "dBaseDSLwin32.l"
{ return '#'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 216 "dBaseDSLwin32.l"
{ return TOK_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 218 "dBaseDSLwin32.l"
{ return '('; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 219 "dBaseDSLwin32.l"
{ return ')'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 220 "dBaseDSLwin32.l"
{ return '['; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 221 "dBaseDSLwin32.l"
{ return ']'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 222 "dBaseDSLwin32.l"
{ return '{'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "dBaseDSLwin32.l"
{ return '}'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 224 "dBaseDSLwin32.l"
{ return ','; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 225 "dBaseDSLwin32.l"
{ return '.'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 227 "dBaseDSLwin32.l"
{
    char buffer[200];
    std::sprintf( buffer, "Unrecognized character: %s\n", yytext );
    yyerror(buffer);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
#line 233 "dBaseDSLwin32.l"
{ return TOK_YYEOF; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 234 "dBaseDSLwin32.l"
ECHO;
	YY_BREAK
#line 1542 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 389 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 389 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 388);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 234 "dBaseDSLwin32.l"


void EXPORT
yy_dbase_win32_lex_parser_error (void (*func)(const char *message)) {
	m_addParserErrorText = func;
}

int yywrap(void) { return 1; }

void yyerror(const char* m)
{
	char * buffer = (char *) malloc(1024);
	char * number = (char *) malloc( 255);
	
	itoa(yy_row,number,10);
	
	strcpy( buffer, "error in line: ");
	strcat( buffer, number);
	strcat( buffer, ": ");
	strcat( buffer, m);

	m_addParserErrorText(buffer);
}

BOOL EXPORT
yy_dbase_win32_lex_main(
    char* filename,
    char* tempDir )
{
    BOOL   result = FALSE;
    char * buffer;

    // ------------------------------------------
    // try to open file, saved before ...
    // ------------------------------------------
    if (!(yyin = fopen(filename,"r"))) {
        buffer = (char*) malloc(100);

        std::sprintf(buffer, "could not open file: %s", filename);
        m_addParserErrorText(buffer);

        free(buffer);
        return false;
    }

    yy_row = 1;
    yy_col = 1;

	// ------------------------------------------
	// start the race run ...
	// ------------------------------------------
	node_head        = (struct node *) malloc( sizeof( struct node ) );
	node_new         = (struct node *) malloc( sizeof( struct node ) ); // dummy to point head itself
	node_head->token = (       char *) malloc( 8 );
	strcpy( node_head->token, "root" );

	// ------------------------
	// root/first record item
	// ------------------------
	node_new->prev = node_head;
	node_new->next = NULL;
	
	// ------------------------
	// call parser ...
	// ------------------------
	result = yyparse();
	
	fclose(yyin);
	return result;
}

void EXPORT
yy_dbase_win32_lex_close(void) {
    fclose(yyin);
}


